name: butil
grade: stable
version: ###VERSION###
summary: Backup your data. Import photos from phone via WI-FI and more.
description: |
  Backup your data. Import photos from phone via WI-FI and more.
  Features include
  - Incremental backup with deduplication of files and FTPS, SMB/CIFS transports support;
  - Import media - Import audios, photos, videos from SD Card of camera, recorder; photos and videos from your phone via WI-FI through FTPS Server application using template file names;
  - Console for automation scheduling;
  - Strong 7-zip compression and AES-256 encryption.
  Minimum Ubuntu version should be 23.10.
license: GPL-3.0+ OR MIT OR MS-PL
issues: https://github.com/drweb86/butil/issues

base: core22

architectures:
  - ###SnapcraftArchitectureLinux###

confinement: classic
compression: lzo

apps:
  ui:
    command: bin/butil-ui.Desktop

  cli:
    command: bin/butilc

parts:
  butil:
    plugin: dotnet
    source: .
    dotnet-build-configuration: Release
    build-packages:
      - dotnet-sdk-7.0
    override-build: |     
      cd ./sources
      dotnet publish /p:Version=###VERSION### /p:AssemblyVersion=###VERSION### -r ###CoreRuntimeLinux### -c Release --self-contained true -o $SNAPCRAFT_PART_INSTALL/bin/
      chmod 0755 $SNAPCRAFT_PART_INSTALL/bin/butil-ui.Desktop
      chmod 0755 $SNAPCRAFT_PART_INSTALL/bin/butilc
    stage-packages:
      - 7zip
      - libicu70
      - libx11-6
      - libstdc++5
      - libice6
      - libsm6

lint:
  ignore:
    - classic
    - library