//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUtil.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUtil.Core.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7z message:.
        /// </summary>
        public static string _7ZMessage {
            get {
                return ResourceManager.GetString("_7ZMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted by user!.
        /// </summary>
        public static string AbortedByUser {
            get {
                return ResourceManager.GetString("AbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After backup task: .
        /// </summary>
        public static string AfterBackupTask {
            get {
                return ResourceManager.GetString("AfterBackupTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured\n\nPlease contact the developers with information saved on your desktop in\n&quot;{0}&quot;\n\nApplication will now close.
        /// </summary>
        public static string AnUnexpectedErrorOccuredNNpleaseContactTheDevelopersWithInformationSavedOnYourDesktopInN0NNapplicationWillNowClose {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccuredNNpleaseContactTheDevelopersWithInformationSavedOnYourDes" +
                        "ktopInN0NNapplicationWillNowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivator: Fatal error.
        /// </summary>
        public static string ArchivatorFatalError {
            get {
                return ResourceManager.GetString("ArchivatorFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivator: Not enough memory for operation.
        /// </summary>
        public static string ArchivatorNotEnoughMemoryForOperation {
            get {
                return ResourceManager.GetString("ArchivatorNotEnoughMemoryForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivator: Warning (Non fatal error(s)). For example, one or more files were locked by some other application, so they were not compressed.
        /// </summary>
        public static string ArchivatorWarningNonFatalErrorSForExampleOneOrMoreFilesWereLockedBySomeOtherApplicationSoTheyWereNotCompressed {
            get {
                return ResourceManager.GetString("ArchivatorWarningNonFatalErrorSForExampleOneOrMoreFilesWereLockedBySomeOtherAppli" +
                        "cationSoTheyWereNotCompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for support.
        /// </summary>
        public static string AskForSupport {
            get {
                return ResourceManager.GetString("AskForSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup finished succesfully!.
        /// </summary>
        public static string BackupFinishedSuccesfully {
            get {
                return ResourceManager.GetString("BackupFinishedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Report.
        /// </summary>
        public static string BackupReport {
            get {
                return ResourceManager.GetString("BackupReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before backup task: .
        /// </summary>
        public static string BeforeBackupTask {
            get {
                return ResourceManager.GetString("BeforeBackupTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUtil software package 7-zip component &apos;{0}&apos; has invalid check summ. \nProbably, it was damaged by viruses. \n\nYou should reinstall application.\n\nRestoration and Backup functions will be unavailable..
        /// </summary>
        public static string ButilSoftwarePackage7ZipComponent0HasInvalidCheckSummNprobablyItWasDamagedByVirusesNNyouShouldReinstallApplicationNNrestorationAndBackupFunctionsWillBeUnavailable {
            get {
                return ResourceManager.GetString("ButilSoftwarePackage7ZipComponent0HasInvalidCheckSummNprobablyItWasDamagedByVirus" +
                        "esNNyouShouldReinstallApplicationNNrestorationAndBackupFunctionsWillBeUnavailabl" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run 7zg.exe because {0}.
        /// </summary>
        public static string CannotRun7ZgExeBecause0 {
            get {
                return ResourceManager.GetString("CannotRun7ZgExeBecause0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation is not equal to password.
        /// </summary>
        public static string ConfirmationIsNotEqualToPassword {
            get {
                return ResourceManager.GetString("ConfirmationIsNotEqualToPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying file &apos;{0}&apos; from temp folder &apos;{1}&apos; to destination &apos;{2}&apos; at {3}.
        /// </summary>
        public static string CopyingFile0FromTempFolder1ToDestination2At3 {
            get {
                return ResourceManager.GetString("CopyingFile0FromTempFolder1ToDestination2At3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying of backup to &apos;{0}&apos; network storage skipped because its size {1} exceeded specified limit {2}.
        /// </summary>
        public static string CopyingOfBackupTo0NetworkStorageSkippedBecauseItsSize1ExceededSpecifiedLimit2 {
            get {
                return ResourceManager.GetString("CopyingOfBackupTo0NetworkStorageSkippedBecauseItsSize1ExceededSpecifiedLimit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy to clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not kill packer process: {0}.
        /// </summary>
        public static string CouldNotKillPackerProcess0 {
            get {
                return ResourceManager.GetString("CouldNotKillPackerProcess0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not kill process &apos;{0}&apos;: {1}.
        /// </summary>
        public static string CouldNotKillProcess01 {
            get {
                return ResourceManager.GetString("CouldNotKillProcess01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start packer due to {0}. Aborting backup....
        /// </summary>
        public static string CouldNotStartPackerDueTo0AbortingBackup {
            get {
                return ResourceManager.GetString("CouldNotStartPackerDueTo0AbortingBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start process &apos;{0}&apos;: {1}.
        /// </summary>
        public static string CouldNotStartProcess01 {
            get {
                return ResourceManager.GetString("CouldNotStartProcess01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coult not run &apos;{0}&apos; due to:\n{1}.
        /// </summary>
        public static string CoultNotRun0DueToN1 {
            get {
                return ResourceManager.GetString("CoultNotRun0DueToN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During deleting of a file &apos;{0}&apos; an error occured: {1}.
        /// </summary>
        public static string DuringDeletingOfAFile0AnErrorOccured1 {
            get {
                return ResourceManager.GetString("DuringDeletingOfAFile0AnErrorOccured1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During overwriting file &apos;{0}&apos; with zeros an error occured: {1}.
        /// </summary>
        public static string DuringOverwritingFile0WithZerosAnErrorOccured1 {
            get {
                return ResourceManager.GetString("DuringOverwritingFile0WithZerosAnErrorOccured1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During packing files to an image &apos;{0}&apos; an error occured: {1}.
        /// </summary>
        public static string DuringPackingFilesToAnImage0AnErrorOccured1 {
            get {
                return ResourceManager.GetString("DuringPackingFilesToAnImage0AnErrorOccured1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password:.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - BUtil.
        /// </summary>
        public static string ErrorButil {
            get {
                return ResourceManager.GetString("ErrorButil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error discovered when copying file to storage &apos;{0}&apos;: {1}.
        /// </summary>
        public static string ErrorDiscoveredWhenCopyingFileToStorage01 {
            get {
                return ResourceManager.GetString("ErrorDiscoveredWhenCopyingFileToStorage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error discovered when opening storage &apos;{0}&apos;: {1}.
        /// </summary>
        public static string ErrorDiscoveredWhenOpeningStorage01 {
            get {
                return ResourceManager.GetString("ErrorDiscoveredWhenOpeningStorage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Compression.
        /// </summary>
        public static string FastCompression {
            get {
                return ResourceManager.GetString("FastCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest Compression.
        /// </summary>
        public static string FastestCompression {
            get {
                return ResourceManager.GetString("FastestCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was copyied to storage successfully.
        /// </summary>
        public static string FileWasCopyiedToStorageSuccessfully {
            get {
                return ResourceManager.GetString("FileWasCopyiedToStorageSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Succesfully.
        /// </summary>
        public static string FinishedSuccesfully {
            get {
                return ResourceManager.GetString("FinishedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished With Errors.
        /// </summary>
        public static string FinishedWithErrors {
            get {
                return ResourceManager.GetString("FinishedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new random password.
        /// </summary>
        public static string GenerateNewRandomPassword {
            get {
                return ResourceManager.GetString("GenerateNewRandomPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Here is your password&gt;.
        /// </summary>
        public static string HereIsYourPassword {
            get {
                return ResourceManager.GetString("HereIsYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information - BUtil.
        /// </summary>
        public static string InformationButil {
            get {
                return ResourceManager.GetString("InformationButil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress....
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is a backup tool for running on computer. For more information see Manual.
        /// </summary>
        public static string IsABackupToolForRunningOnComputerForMoreInformationSeeManual {
            get {
                return ResourceManager.GetString("IsABackupToolForRunningOnComputerForMoreInformationSeeManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localization options are not setted.
        /// </summary>
        public static string LocalizationOptionsAreNotSetted {
            get {
                return ResourceManager.GetString("LocalizationOptionsAreNotSetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Compression.
        /// </summary>
        public static string MaximumCompression {
            get {
                return ResourceManager.GetString("MaximumCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Compression.
        /// </summary>
        public static string NormalCompression {
            get {
                return ResourceManager.GetString("NormalCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Password length should be more than 20 characters and less than 257 characters\r\n.
        /// </summary>
        public static string NotePasswordLengthShouldBeMoreThan20CharactersAndLessThan257CharactersRN {
            get {
                return ResourceManager.GetString("NotePasswordLengthShouldBeMoreThan20CharactersAndLessThan257CharactersRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing aborted: component of an image file &apos;{0}&apos; does not exist(Is it enough space in temporary folder ?).
        /// </summary>
        public static string PackingAbortedComponentOfAnImageFile0DoesNotExistIsItEnoughSpaceInTemporaryFolder {
            get {
                return ResourceManager.GetString("PackingAbortedComponentOfAnImageFile0DoesNotExistIsItEnoughSpaceInTemporaryFolder" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing of data to an image was aborted by user.
        /// </summary>
        public static string PackingOfDataToAnImageWasAbortedByUser {
            get {
                return ResourceManager.GetString("PackingOfDataToAnImageWasAbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password contains forbidden characters! Please remove spaces.
        /// </summary>
        public static string PasswordContainsForbiddenCharactersPleaseRemoveSpaces {
            get {
                return ResourceManager.GetString("PasswordContainsForbiddenCharactersPleaseRemoveSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password generator.
        /// </summary>
        public static string PasswordGenerator {
            get {
                return ResourceManager.GetString("PasswordGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has invalid length. Password length should be from {0} to {1} characters.
        /// </summary>
        public static string PasswordHasInvalidLengthPasswordLengthShouldBeFrom0To1Characters {
            get {
                return ResourceManager.GetString("PasswordHasInvalidLengthPasswordLengthShouldBeFrom0To1Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (if needed).
        /// </summary>
        public static string PasswordIfNeeded {
            get {
                return ResourceManager.GetString("PasswordIfNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid.\n\nIt was reseted\n.
        /// </summary>
        public static string PasswordIsInvalidNNitWasResetedN {
            get {
                return ResourceManager.GetString("PasswordIsInvalidNNitWasResetedN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length:.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm deletion of {0} logs..
        /// </summary>
        public static string PleaseConfirmDeletionOf0Logs {
            get {
                return ResourceManager.GetString("PleaseConfirmDeletionOf0Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, report this bug to me! Archivator: Command line error.
        /// </summary>
        public static string PleaseReportThisBugToMeArchivatorCommandLineError {
            get {
                return ResourceManager.GetString("PleaseReportThisBugToMeArchivatorCommandLineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question - BUtil.
        /// </summary>
        public static string QuestionButil {
            get {
                return ResourceManager.GetString("QuestionButil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        public static string ReportABug {
            get {
                return ResourceManager.GetString("ReportABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Warning\n\nYour password was saved insecurely as plain text in file &apos;{0}&apos; because &apos;{1}&apos;\n\nTo store passwords securely please:\n- check that you use NTFS file system at system drive,\n- your Windows version supports encrypted file system EFS..
        /// </summary>
        public static string SecurityWarningNNyourPasswordWasSavedInsecurelyAsPlainTextInFile0Because1NNtoStorePasswordsSecurelyPleaseNCheckThatYouUseNtfsFileSystemAtSystemDriveNYourWindowsVersionSupportsEncryptedFileSystemEfs {
            get {
                return ResourceManager.GetString("SecurityWarningNNyourPasswordWasSavedInsecurelyAsPlainTextInFile0Because1NNtoStor" +
                        "ePasswordsSecurelyPleaseNCheckThatYouUseNtfsFileSystemAtSystemDriveNYourWindowsV" +
                        "ersionSupportsEncryptedFileSystemEfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &apos;{0}&apos; requires option &apos;enable encryption&apos; to be enabled. But in your case it was disabled. Copying to storage skipped..
        /// </summary>
        public static string Storage0RequiresOptionEnableEncryptionToBeEnabledButInYourCaseItWasDisabledCopyingToStorageSkipped {
            get {
                return ResourceManager.GetString("Storage0RequiresOptionEnableEncryptionToBeEnabledButInYourCaseItWasDisabledCopyin" +
                        "gToStorageSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest a feature.
        /// </summary>
        public static string SuggestAFeature {
            get {
                return ResourceManager.GetString("SuggestAFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data to backup specified in configuration.
        /// </summary>
        public static string ThereIsNoDataToBackupSpecifiedInConfiguration {
            get {
                return ResourceManager.GetString("ThereIsNoDataToBackupSpecifiedInConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no storages specified in configuration. Compression of data was skipped.
        /// </summary>
        public static string ThereIsNoStoragesSpecifiedInConfigurationCompressionOfDataWasSkipped {
            get {
                return ResourceManager.GetString("ThereIsNoStoragesSpecifiedInConfigurationCompressionOfDataWasSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra Compression.
        /// </summary>
        public static string UltraCompression {
            get {
                return ResourceManager.GetString("UltraCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User stopped the process.
        /// </summary>
        public static string UserStoppedTheProcess {
            get {
                return ResourceManager.GetString("UserStoppedTheProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit project homepage.
        /// </summary>
        public static string VisitProjectHomepage {
            get {
                return ResourceManager.GetString("VisitProjectHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Compression.
        /// </summary>
        public static string WithoutCompression {
            get {
                return ResourceManager.GetString("WithoutCompression", resourceCulture);
            }
        }
    }
}
