//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUtil.Tools.Md5.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUtil.Tools.Md5.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line arguments:\n\nhelp\n  Shows this help\n\ndev\n  Shows md5 summs of packer and internally stored md5 checksumms\n\nmd5 &quot;&lt;filename&gt;&quot;\n  Shows md5 of a specified file\n\nverify &quot;&lt;filename&gt;&quot;\n  Compares md5 of a specified file with it&apos;s .md5\n\nverify &quot;&lt;filename&gt;&quot; &quot;&lt;file with md5&gt;&quot;\n  Compares md5 of a specified file md5 stored in second file\n\nsign &quot;&lt;filename&gt;&quot;\n  Signs file with md5 and stores computed md5 in &quot;&lt;filename&gt;&quot;.md5\n\nsign &quot;&lt;filename&gt;&quot; &quot;&lt;file where to store md5&gt;&quot;\n  Signs file with md [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommandLineArgumentsNNhelpNShowsThisHelpNNdevNShowsMd5SummsOfPackerAndInternallyStoredMd5ChecksummsNNmd5FilenameNShowsMd5OfASpecifiedFileNNverifyFilenameNComparesMd5OfASpecifiedFileWithItsMd5NNverifyFilenameFileWithMd5NComparesMd5OfASpecifiedFileMd5StoredInSecondFileNNsignFilenameNSignsFileWithMd5AndStoresComputedMd5InFilenameMd5NNsignFilenameFileWhereToStoreMd5NSignsFileWithMd5AndStoresComputedMd5InSecondFile {
            get {
                return ResourceManager.GetString(@"CommandLineArgumentsNNhelpNShowsThisHelpNNdevNShowsMd5SummsOfPackerAndInternallyStoredMd5ChecksummsNNmd5FilenameNShowsMd5OfASpecifiedFileNNverifyFilenameNComparesMd5OfASpecifiedFileWithItsMd5NNverifyFilenameFileWithMd5NComparesMd5OfASpecifiedFileMd5StoredInSecondFileNNsignFilenameNSignsFileWithMd5AndStoresComputedMd5InFilenameMd5NNsignFilenameFileWhereToStoreMd5NSignsFileWithMd5AndStoresComputedMd5InSecondFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRECT\n.
        /// </summary>
        internal static string CorrectN {
            get {
                return ResourceManager.GetString("CorrectN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does NOT match\n.
        /// </summary>
        internal static string DoesNotMatchN {
            get {
                return ResourceManager.GetString("DoesNotMatchN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Parameter 1(or just &lt;Enter&gt; if there&apos;s no parameter 1 in command): .
        /// </summary>
        internal static string EnterParameter1OrJustEnterIfTheresNoParameter1InCommand {
            get {
                return ResourceManager.GetString("EnterParameter1OrJustEnterIfTheresNoParameter1InCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Parameter 2(or just &lt;Enter&gt; if there&apos;s no parameter 2 in command): .
        /// </summary>
        internal static string EnterParameter2OrJustEnterIfTheresNoParameter2InCommand {
            get {
                return ResourceManager.GetString("EnterParameter2OrJustEnterIfTheresNoParameter2InCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file wasn&apos;t specified.
        /// </summary>
        internal static string InputFileWasntSpecified {
            get {
                return ResourceManager.GetString("InputFileWasntSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5Signer - commands.
        /// </summary>
        internal static string Md5signerCommands {
            get {
                return ResourceManager.GetString("Md5signerCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5Signer - Question.
        /// </summary>
        internal static string Md5signerQuestion {
            get {
                return ResourceManager.GetString("Md5signerQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failled:\n{0}.
        /// </summary>
        internal static string OperationFailledN0 {
            get {
                return ResourceManager.GetString("OperationFailledN0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not supported.
        /// </summary>
        internal static string OperationNotSupported {
            get {
                return ResourceManager.GetString("OperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter command: .
        /// </summary>
        internal static string PleaseEnterCommand {
            get {
                return ResourceManager.GetString("PleaseEnterCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to quit.
        /// </summary>
        internal static string PressAnyKeyToQuit {
            get {
                return ResourceManager.GetString("PressAnyKeyToQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to enter required arguments in interactive mode?.
        /// </summary>
        internal static string WouldYouLikeToEnterRequiredArgumentsInInteractiveMode {
            get {
                return ResourceManager.GetString("WouldYouLikeToEnterRequiredArgumentsInInteractiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t specified parameter(s).
        /// </summary>
        internal static string YouDidntSpecifiedParameterS {
            get {
                return ResourceManager.GetString("YouDidntSpecifiedParameterS", resourceCulture);
            }
        }
    }
}
