<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugSymbols>False</DebugSymbols>
    <DebugType>None</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../BUtil.Core/BUtil.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\ValidationError.axaml.cs">
      <DependentUpon>ValidationError.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\ViewDecoration.axaml.cs">
      <DependentUpon>ViewDecoration.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\TextField.axaml.cs">
      <DependentUpon>TextField.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\CheckboxField.axaml.cs">
      <DependentUpon>CheckboxField.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\DateField.axaml.cs">
      <DependentUpon>DateField.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\DropdownField.axaml.cs">
      <DependentUpon>DropdownField.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\ExpanderHeader.axaml.cs">
      <DependentUpon>ExpanderHeader.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\NumericUpDownField.axaml.cs">
      <DependentUpon>NumericUpDownField.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\TextFieldWithAction.axaml.cs">
      <DependentUpon>TextFieldWithAction.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\IconButton.axaml.cs">
      <DependentUpon>IconButton.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\GridRowButton.axaml.cs">
      <DependentUpon>GridRowButton.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\MessageBar.axaml.cs">
      <DependentUpon>MessageBar.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\FormHeader.axaml.cs">
      <DependentUpon>FormHeader.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\DialogButtons.axaml.cs">
      <DependentUpon>DialogButtons.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\ConfirmPanel.axaml.cs">
      <DependentUpon>ConfirmPanel.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
