//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUtil.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUtil.Core.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        public static string AfterTaskSelection_DoNothing {
            get {
                return ResourceManager.GetString("AfterTaskSelection_DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After task completion:.
        /// </summary>
        public static string AfterTaskSelection_Field {
            get {
                return ResourceManager.GetString("AfterTaskSelection_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you choose something other than &apos;do nothing&apos; 
        ///program will configure OS to show you report
        ///on next your logon to the system if any errors 
        ///or warnings will be registered..
        /// </summary>
        public static string AfterTaskSelection_Help {
            get {
                return ResourceManager.GetString("AfterTaskSelection_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string AfterTaskSelection_LogOff {
            get {
                return ResourceManager.GetString("AfterTaskSelection_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        public static string AfterTaskSelection_Reboot {
            get {
                return ResourceManager.GetString("AfterTaskSelection_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string AfterTaskSelection_ShutdownPc {
            get {
                return ResourceManager.GetString("AfterTaskSelection_ShutdownPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0} version is available.
        ///
        ///Changes are:
        ///{1}
        ///
        ///Program will now open browser with the download page.
        /// </summary>
        public static string Application_NewVersion_Notification {
            get {
                return ResourceManager.GetString("Application_NewVersion_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGES.
        /// </summary>
        public static string BackupVersion_Changes_Title {
            get {
                return ResourceManager.GetString("BackupVersion_Changes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete uncompleted backups.
        /// </summary>
        public static string BackupVersion_CleanupUncompleted {
            get {
                return ResourceManager.GetString("BackupVersion_CleanupUncompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILES.
        /// </summary>
        public static string BackupVersion_Files_Title {
            get {
                return ResourceManager.GetString("BackupVersion_Files_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal: {0}.
        /// </summary>
        public static string BackupVersion_FileVersion_Title {
            get {
                return ResourceManager.GetString("BackupVersion_FileVersion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal for selected....
        /// </summary>
        public static string BackupVersion_FileVersions_Open {
            get {
                return ResourceManager.GetString("BackupVersion_FileVersions_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open selected version....
        /// </summary>
        public static string BackupVersion_Select {
            get {
                return ResourceManager.GetString("BackupVersion_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT VERSION.
        /// </summary>
        public static string BackupVersion_Selector_Title {
            get {
                return ResourceManager.GetString("BackupVersion_Selector_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage: {0}.
        /// </summary>
        public static string BackupVersion_Storage_TitleWithSize {
            get {
                return ResourceManager.GetString("BackupVersion_Storage_TitleWithSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERSIONS.
        /// </summary>
        public static string BackupVersion_Versions_Title {
            get {
                return ResourceManager.GetString("BackupVersion_Versions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on item you want to restore and open context menu by right click..
        /// </summary>
        public static string BackupVersion_Viewer_Help {
            get {
                return ResourceManager.GetString("BackupVersion_Viewer_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue &gt;.
        /// </summary>
        public static string Button_Continue {
            get {
                return ResourceManager.GetString("Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Button_CopyToClipboard {
            get {
                return ResourceManager.GetString("Button_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit {0} to see command line arguments..
        /// </summary>
        public static string CommandLineArguments_Help {
            get {
                return ResourceManager.GetString("CommandLineArguments_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command line arguments..
        /// </summary>
        public static string CommandLineArguments_Invalid {
            get {
                return ResourceManager.GetString("CommandLineArguments_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection script:.
        /// </summary>
        public static string DataStorage_Field_ConnectScript {
            get {
                return ResourceManager.GetString("DataStorage_Field_ConnectScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnection script:.
        /// </summary>
        public static string DataStorage_Field_DisconnectionScript {
            get {
                return ResourceManager.GetString("DataStorage_Field_DisconnectionScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished with errors.
        /// </summary>
        public static string DataStorage_Field_DisconnectionScript_Bad {
            get {
                return ResourceManager.GetString("DataStorage_Field_DisconnectionScript_Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished succesfully.
        /// </summary>
        public static string DataStorage_Field_DisconnectionScript_Ok {
            get {
                return ResourceManager.GetString("DataStorage_Field_DisconnectionScript_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload limit, GB:.
        /// </summary>
        public static string DataStorage_Field_UploadQuota {
            get {
                return ResourceManager.GetString("DataStorage_Field_UploadQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits amount of data being sent during one task execution to storage. 0 - no limit.
        ///When quota is exceeded, other files will be skipped and will be processed next time.
        ///Usage scenario: You copy data to remote server. There&apos;s a problem: ISP drops upload speed after several gigabytes. This setting allows you to handle it..
        /// </summary>
        public static string DataStorage_Field_UploadQuota_Help {
            get {
                return ResourceManager.GetString("DataStorage_Field_UploadQuota_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota should be 0 (do not apply) or value above 0..
        /// </summary>
        public static string DataStorage_Field_UploadQuota_Validation {
            get {
                return ResourceManager.GetString("DataStorage_Field_UploadQuota_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If folder becomes available after executing some commands, specify PowerShell scripts for connection and disconnection..
        /// </summary>
        public static string DataStorage_Script_Help {
            get {
                return ResourceManager.GetString("DataStorage_Script_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get state of storage.
        /// </summary>
        public static string DataStorage_State_Get {
            get {
                return ResourceManager.GetString("DataStorage_State_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage is not specified..
        /// </summary>
        public static string DataStorage_Validation_NotSpecified {
            get {
                return ResourceManager.GetString("DataStorage_Validation_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose days of week:.
        /// </summary>
        public static string Days_Field_Choose {
            get {
                return ResourceManager.GetString("Days_Field_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Days_Friday {
            get {
                return ResourceManager.GetString("Days_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Days_Monday {
            get {
                return ResourceManager.GetString("Days_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Days_Saturday {
            get {
                return ResourceManager.GetString("Days_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Days_Sunday {
            get {
                return ResourceManager.GetString("Days_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Days_Thursday {
            get {
                return ResourceManager.GetString("Days_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Days_Tuesday {
            get {
                return ResourceManager.GetString("Days_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Days_Wednesday {
            get {
                return ResourceManager.GetString("Days_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string DirectoryStorage {
            get {
                return ResourceManager.GetString("DirectoryStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder:.
        /// </summary>
        public static string DirectoryStorage_Field_Directory {
            get {
                return ResourceManager.GetString("DirectoryStorage_Field_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is not specified..
        /// </summary>
        public static string DirectoryStorage_Field_Directory_Validation_Empty {
            get {
                return ResourceManager.GetString("DirectoryStorage_Field_Directory_Validation_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &quot;{0}&quot; does not exist..
        /// </summary>
        public static string DirectoryStorage_Field_Directory_Validation_NotFound {
            get {
                return ResourceManager.GetString("DirectoryStorage_Field_Directory_Validation_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder:.
        /// </summary>
        public static string Field_Folder {
            get {
                return ResourceManager.GetString("Field_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exist..
        /// </summary>
        public static string Field_Folder_Validation_NotExist {
            get {
                return ResourceManager.GetString("Field_Folder_Validation_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrity verification script.ps1.
        /// </summary>
        public static string File_IntegrityVerificationScript_Ps1 {
            get {
                return ResourceManager.GetString("File_IntegrityVerificationScript_Ps1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving integrity verification scripts.
        /// </summary>
        public static string File_IntegrityVerificationScript_Saving {
            get {
                return ResourceManager.GetString("File_IntegrityVerificationScript_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving files.
        /// </summary>
        public static string File_List_Saving {
            get {
                return ResourceManager.GetString("File_List_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving &quot;{0}&quot;.
        /// </summary>
        public static string File_Saving {
            get {
                return ResourceManager.GetString("File_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit.
        /// </summary>
        public static string Ftps_Encryption_Option_Explicit {
            get {
                return ResourceManager.GetString("Ftps_Encryption_Option_Explicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implicit.
        /// </summary>
        public static string Ftps_Encryption_Option_Implicit {
            get {
                return ResourceManager.GetString("Ftps_Encryption_Option_Implicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL/TTS encryption:.
        /// </summary>
        public static string Ftps_Field_Encryption {
            get {
                return ResourceManager.GetString("Ftps_Field_Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import all files.
        /// </summary>
        public static string ImportMediaTask_AllFiles {
            get {
                return ResourceManager.GetString("ImportMediaTask_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create import media task.
        /// </summary>
        public static string ImportMediaTask_Create {
            get {
                return ResourceManager.GetString("ImportMediaTask_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &quot;{0}&quot; media import task.
        /// </summary>
        public static string ImportMediaTask_Edit_Title {
            get {
                return ResourceManager.GetString("ImportMediaTask_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder:.
        /// </summary>
        public static string ImportMediaTask_Field_OutputFolder {
            get {
                return ResourceManager.GetString("ImportMediaTask_Field_OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name transformations:.
        /// </summary>
        public static string ImportMediaTask_Field_TransformFileName {
            get {
                return ResourceManager.GetString("ImportMediaTask_Field_TransformFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported tokens:
        ///{DATE:Format} - Inserts file modification date in the specified format.
        ///To see all options google &quot;C# DateTime format&quot;..
        /// </summary>
        public static string ImportMediaTask_Field_TransformFileName_Help {
            get {
                return ResourceManager.GetString("ImportMediaTask_Field_TransformFileName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform file name is empty..
        /// </summary>
        public static string ImportMediaTask_Field_TransformFileName_Validation_Empty {
            get {
                return ResourceManager.GetString("ImportMediaTask_Field_TransformFileName_Validation_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transform file name string..
        /// </summary>
        public static string ImportMediaTask_Field_TransformFileName_Validation_Invalid {
            get {
                return ResourceManager.GetString("ImportMediaTask_Field_TransformFileName_Validation_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import &quot;{0}&quot;.
        /// </summary>
        public static string ImportMediaTask_File {
            get {
                return ResourceManager.GetString("ImportMediaTask_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports audios, photos, videos from SD Card of camera, recorder;
        ///photos and videos from your phone via WI-FI through FTP Server 
        ///application using template file names..
        /// </summary>
        public static string ImportMediaTask_Help {
            get {
                return ResourceManager.GetString("ImportMediaTask_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data source.
        /// </summary>
        public static string ImportMediaTask_ImportDataSource {
            get {
                return ResourceManager.GetString("ImportMediaTask_ImportDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip already imported files.
        /// </summary>
        public static string ImportMediaTask_SkipAlreadyImportedFiles {
            get {
                return ResourceManager.GetString("ImportMediaTask_SkipAlreadyImportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured
        ///
        ///Please contact the developers with information saved on your desktop in
        ///&quot;{0}&quot;
        ///
        ///Application will now close.
        /// </summary>
        public static string ImproveIt_Message {
            get {
                return ResourceManager.GetString("ImproveIt_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most basic form of incremental backup consists of identifying, recording and thus, preserving only those files that have changed since the last backup.
        ///Since changes are typically low, incremental backups are much smaller and quicker than full backups.
        ///For instance, following a full backup on Friday, a Monday backup will contain only those files that changed since Friday. A Tuesday backup contains only those files that changed since Monday, and so on. 
        ///Should any one of the copies created fail, inclu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IncrementalBackup_Help {
            get {
                return ResourceManager.GetString("IncrementalBackup_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremental backup.
        /// </summary>
        public static string IncrementalBackup_Title {
            get {
                return ResourceManager.GetString("IncrementalBackup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate incremented version.
        /// </summary>
        public static string IncrementalBackup_Version_Calculate {
            get {
                return ResourceManager.GetString("IncrementalBackup_Version_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving incremented version.
        /// </summary>
        public static string IncrementalBackup_Version_Save {
            get {
                return ResourceManager.GetString("IncrementalBackup_Version_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create incremental backup task.
        /// </summary>
        public static string IncrementalBackupTask_Create {
            get {
                return ResourceManager.GetString("IncrementalBackupTask_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption.
        /// </summary>
        public static string LeftMenu_Encryption {
            get {
                return ResourceManager.GetString("LeftMenu_Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What?.
        /// </summary>
        public static string LeftMenu_What {
            get {
                return ResourceManager.GetString("LeftMenu_What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you may add folders and files you need to process..
        /// </summary>
        public static string LeftMenu_What_Hint {
            get {
                return ResourceManager.GetString("LeftMenu_What_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to process..
        /// </summary>
        public static string LeftMenu_What_Validation {
            get {
                return ResourceManager.GetString("LeftMenu_What_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When?.
        /// </summary>
        public static string LeftMenu_When {
            get {
                return ResourceManager.GetString("LeftMenu_When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can set up a scheduler. Shceduler can help you to automate task launch..
        /// </summary>
        public static string LeftMenu_When_Help {
            get {
                return ResourceManager.GetString("LeftMenu_When_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where?.
        /// </summary>
        public static string LeftMenu_Where {
            get {
                return ResourceManager.GetString("LeftMenu_Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop here files and folders from Explorer..
        /// </summary>
        public static string LeftMenu_Where_Help_DragDrop {
            get {
                return ResourceManager.GetString("LeftMenu_Where_Help_DragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this place you can add locations where you would like your files to be copied..
        /// </summary>
        public static string LeftMenu_Where_Hint {
            get {
                return ResourceManager.GetString("LeftMenu_Where_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string LogFile_Marker_Errors {
            get {
                return ResourceManager.GetString("LogFile_Marker_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string LogFile_Marker_Successful {
            get {
                return ResourceManager.GetString("LogFile_Marker_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string LogFile_OpenLogs {
            get {
                return ResourceManager.GetString("LogFile_OpenLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Messages_Header_Error {
            get {
                return ResourceManager.GetString("Messages_Header_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Messages_Header_Information {
            get {
                return ResourceManager.GetString("Messages_Header_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Messages_Header_Question {
            get {
                return ResourceManager.GetString("Messages_Header_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name_Field {
            get {
                return ResourceManager.GetString("Name_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is empty or contains not supported path characters..
        /// </summary>
        public static string Name_Field_Validation {
            get {
                return ResourceManager.GetString("Name_Field_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name_Title {
            get {
                return ResourceManager.GetString("Name_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password_Field {
            get {
                return ResourceManager.GetString("Password_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        public static string Password_Field_Confirm {
            get {
                return ResourceManager.GetString("Password_Field_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        public static string Password_Field_Length {
            get {
                return ResourceManager.GetString("Password_Field_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string Password_Field_Validation_NotMatch {
            get {
                return ResourceManager.GetString("Password_Field_Validation_NotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not specified..
        /// </summary>
        public static string Password_Field_Validation_NotSpecified {
            get {
                return ResourceManager.GetString("Password_Field_Validation_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate password....
        /// </summary>
        public static string Password_Generate {
            get {
                return ResourceManager.GetString("Password_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password generator.
        /// </summary>
        public static string Password_Generator_Header {
            get {
                return ResourceManager.GetString("Password_Generator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (optional).
        /// </summary>
        public static string Password_Group_Header {
            get {
                return ResourceManager.GetString("Password_Group_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended minimum password length is 50 characters and more..
        /// </summary>
        public static string Password_Help {
            get {
                return ResourceManager.GetString("Password_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your backup is password protected, please type password here:.
        /// </summary>
        public static string Password_Recovery_Prompt {
            get {
                return ResourceManager.GetString("Password_Recovery_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Password_Use {
            get {
                return ResourceManager.GetString("Password_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate files &quot;{0}&quot; in directory. 
        ///
        ///Point to a directory containing this file..
        /// </summary>
        public static string RestoreFrom_Field_Validation_NoStateFiles {
            get {
                return ResourceManager.GetString("RestoreFrom_Field_Validation_NoStateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read state..
        /// </summary>
        public static string RestoreFrom_Field_Validation_StateInvalid {
            get {
                return ResourceManager.GetString("RestoreFrom_Field_Validation_StateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name:.
        /// </summary>
        public static string Server_Field_Address {
            get {
                return ResourceManager.GetString("Server_Field_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name is not be specified..
        /// </summary>
        public static string Server_Field_Address_Validation {
            get {
                return ResourceManager.GetString("Server_Field_Address_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string Server_Field_Port {
            get {
                return ResourceManager.GetString("Server_Field_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port is invalid..
        /// </summary>
        public static string Server_Field_Port_Validation {
            get {
                return ResourceManager.GetString("Server_Field_Port_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files....
        /// </summary>
        public static string SourceItem_AddFiles {
            get {
                return ResourceManager.GetString("SourceItem_AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folders....
        /// </summary>
        public static string SourceItem_AddFolders {
            get {
                return ResourceManager.GetString("SourceItem_AddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Explorer....
        /// </summary>
        public static string SourceItem_OpenInExplorer {
            get {
                return ResourceManager.GetString("SourceItem_OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get state of source item &quot;{0}&quot;.
        /// </summary>
        public static string SourceItem_State_Get {
            get {
                return ResourceManager.GetString("SourceItem_State_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to process..
        /// </summary>
        public static string SourceItem_Validation_Empty {
            get {
                return ResourceManager.GetString("SourceItem_Validation_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; does not exist, correct list of source items..
        /// </summary>
        public static string SourceItem_Validation_NotExists {
            get {
                return ResourceManager.GetString("SourceItem_Validation_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get state of file &quot;{0}&quot;.
        /// </summary>
        public static string State_File_Get {
            get {
                return ResourceManager.GetString("State_File_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get state of source items and storages.
        /// </summary>
        public static string State_LoadFromEverywhere {
            get {
                return ResourceManager.GetString("State_LoadFromEverywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing state.
        /// </summary>
        public static string State_Saving {
            get {
                return ResourceManager.GetString("State_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file exclude pattern.
        /// </summary>
        public static string StorageItem_ExcludePattern_Add {
            get {
                return ResourceManager.GetString("StorageItem_ExcludePattern_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit file exclude pattern.
        /// </summary>
        public static string StorageItem_ExcludePattern_Edit {
            get {
                return ResourceManager.GetString("StorageItem_ExcludePattern_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File globbing in .NET: Patterns.
        /// </summary>
        public static string StorageItem_ExcludePattern_GlobbingNetPatterns {
            get {
                return ResourceManager.GetString("StorageItem_ExcludePattern_GlobbingNetPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can specify file globbing exclude patterns. 
        ///It can be a file name or folder name or wildcard. 
        ///Examples: 
        ///d:\temp, 
        ///d:\temp\file.txt, 
        ///d:\temp\**\*.txt or 
        ///bin. 
        ///See detailed description in the following link..
        /// </summary>
        public static string StorageItem_ExcludePattern_Help {
            get {
                return ResourceManager.GetString("StorageItem_ExcludePattern_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skips processing of files by exclude pattern..
        /// </summary>
        public static string StorageItem_ExcludePattern_Hint {
            get {
                return ResourceManager.GetString("StorageItem_ExcludePattern_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exclude pattern:.
        /// </summary>
        public static string StorageItem_Field_ExcludePattern {
            get {
                return ResourceManager.GetString("StorageItem_Field_ExcludePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exclude pattern is empty..
        /// </summary>
        public static string StorageItem_Field_ExcludePattern_Validation {
            get {
                return ResourceManager.GetString("StorageItem_Field_ExcludePattern_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Task_Create {
            get {
                return ResourceManager.GetString("Task_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates new task..
        /// </summary>
        public static string Task_Create_Hint {
            get {
                return ResourceManager.GetString("Task_Create_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Task_Delete {
            get {
                return ResourceManager.GetString("Task_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete &quot;{0}&quot;?.
        /// </summary>
        public static string Task_Delete_Confirm {
            get {
                return ResourceManager.GetString("Task_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the selected task..
        /// </summary>
        public static string Task_Delete_Hint {
            get {
                return ResourceManager.GetString("Task_Delete_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Task_Edit {
            get {
                return ResourceManager.GetString("Task_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edits the selected task..
        /// </summary>
        public static string Task_Edit_Hint {
            get {
                return ResourceManager.GetString("Task_Edit_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot edit this type of task in CLI..
        /// </summary>
        public static string Task_Edit_Validation_NoCLI {
            get {
                return ResourceManager.GetString("Task_Edit_Validation_NoCLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the task:.
        /// </summary>
        public static string Task_Field_Choose {
            get {
                return ResourceManager.GetString("Task_Field_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task.
        /// </summary>
        public static string Task_Field_Name_NewDefaultValue {
            get {
                return ResourceManager.GetString("Task_Field_Name_NewDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Task_LastExecution_State {
            get {
                return ResourceManager.GetString("Task_LastExecution_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Task_Launch {
            get {
                return ResourceManager.GetString("Task_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launches selected task..
        /// </summary>
        public static string Task_Launch_Hint {
            get {
                return ResourceManager.GetString("Task_Launch_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Task_List {
            get {
                return ResourceManager.GetString("Task_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Task_Restore {
            get {
                return ResourceManager.GetString("Task_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed (see opened log).
        /// </summary>
        public static string Task_Status_FailedSeeLog {
            get {
                return ResourceManager.GetString("Task_Status_FailedSeeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task is in a progress....
        /// </summary>
        public static string Task_Status_InProgress {
            get {
                return ResourceManager.GetString("Task_Status_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed partially. Due to storage quota some files were skipped this time. Remaining {0} files with of {1} GB..
        /// </summary>
        public static string Task_Status_PartialDueToQuota {
            get {
                return ResourceManager.GetString("Task_Status_PartialDueToQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfull.
        /// </summary>
        public static string Task_Status_Succesfull {
            get {
                return ResourceManager.GetString("Task_Status_Succesfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Task_Status_Unknown {
            get {
                return ResourceManager.GetString("Task_Status_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &apos;{0}&apos; wasn&apos;t found..
        /// </summary>
        public static string Task_Validation_NotFound {
            get {
                return ResourceManager.GetString("Task_Validation_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task type is not supported..
        /// </summary>
        public static string Task_Validation_NotSupported {
            get {
                return ResourceManager.GetString("Task_Validation_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed:.
        /// </summary>
        public static string Time_Field_Elapsed {
            get {
                return ResourceManager.GetString("Time_Field_Elapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour:.
        /// </summary>
        public static string Time_Field_Hour {
            get {
                return ResourceManager.GetString("Time_Field_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute:.
        /// </summary>
        public static string Time_Field_Minute {
            get {
                return ResourceManager.GetString("Time_Field_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url:.
        /// </summary>
        public static string Url_Field {
            get {
                return ResourceManager.GetString("Url_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url is not specified..
        /// </summary>
        public static string Url_Field_Validation {
            get {
                return ResourceManager.GetString("Url_Field_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string User_Field {
            get {
                return ResourceManager.GetString("User_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not specified..
        /// </summary>
        public static string User_Field_Validation {
            get {
                return ResourceManager.GetString("User_Field_Validation", resourceCulture);
            }
        }
    }
}
