//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUtil.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUtil.Core.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        public static string AfterTaskSelection_DoNothing {
            get {
                return ResourceManager.GetString("AfterTaskSelection_DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After task completion:.
        /// </summary>
        public static string AfterTaskSelection_Field {
            get {
                return ResourceManager.GetString("AfterTaskSelection_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string AfterTaskSelection_LogOff {
            get {
                return ResourceManager.GetString("AfterTaskSelection_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        public static string AfterTaskSelection_Reboot {
            get {
                return ResourceManager.GetString("AfterTaskSelection_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string AfterTaskSelection_ShutdownPc {
            get {
                return ResourceManager.GetString("AfterTaskSelection_ShutdownPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured
        ///
        ///Please contact the developers with information saved on your desktop in
        ///&quot;{0}&quot;
        ///
        ///Application will now close.
        /// </summary>
        public static string AnUnexpectedErrorOccuredNNpleaseContactTheDevelopersWithInformationSavedOnYourDesktopInN0NNapplicationWillNowClose {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccuredNNpleaseContactTheDevelopersWithInformationSavedOnYourDes" +
                        "ktopInN0NNapplicationWillNowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch task.
        /// </summary>
        public static string ApplicationName_LaunchTask {
            get {
                return ResourceManager.GetString("ApplicationName_LaunchTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string ApplicationName_Tasks {
            get {
                return ResourceManager.GetString("ApplicationName_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGES.
        /// </summary>
        public static string BackupVersion_Changes_Title {
            get {
                return ResourceManager.GetString("BackupVersion_Changes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILES.
        /// </summary>
        public static string BackupVersion_Files_Title {
            get {
                return ResourceManager.GetString("BackupVersion_Files_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT VERSION.
        /// </summary>
        public static string BackupVersion_Selector_Title {
            get {
                return ResourceManager.GetString("BackupVersion_Selector_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage: {0}.
        /// </summary>
        public static string BackupVersion_Storage_TitleWithSize {
            get {
                return ResourceManager.GetString("BackupVersion_Storage_TitleWithSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERSIONS.
        /// </summary>
        public static string BackupVersion_Versions_Title {
            get {
                return ResourceManager.GetString("BackupVersion_Versions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup was partial. Due to storage quota some files were not copied. Remaining {0} files with of {1} GB..
        /// </summary>
        public static string BackupWasPartialDueToStorageQuota {
            get {
                return ResourceManager.GetString("BackupWasPartialDueToStorageQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUtil software package component &apos;{0}&apos; is missing.
        ///
        ///Please reinstall application.
        ///
        ///Restoration, Backup and Help functions will be unavailable..
        /// </summary>
        public static string ButilSoftwarePackageComponent0IsMissingNNpleaseReinstallApplicationNNrestorationBackupAndHelpFunctionsWillBeUnavailable {
            get {
                return ResourceManager.GetString("ButilSoftwarePackageComponent0IsMissingNNpleaseReinstallApplicationNNrestorationB" +
                        "ackupAndHelpFunctionsWillBeUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Button_CopyToClipboard {
            get {
                return ResourceManager.GetString("Button_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate incremented version.
        /// </summary>
        public static string CalculateIncrementedVersionForStorage {
            get {
                return ResourceManager.GetString("CalculateIncrementedVersionForStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate file &quot;{0}&quot; in directory. 
        ///
        ///Point to a directory containing this file..
        /// </summary>
        public static string CannotLocateFile0InDirectoryPointToADirectoryContainingThisFile {
            get {
                return ResourceManager.GetString("CannotLocateFile0InDirectoryPointToADirectoryContainingThisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open backup folder..
        /// </summary>
        public static string CannotOpenBackupFolder {
            get {
                return ResourceManager.GetString("CannotOpenBackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file log due to crytical error {0}.
        /// </summary>
        public static string CannotOpenFileLogDueToCryticalError0 {
            get {
                return ResourceManager.GetString("CannotOpenFileLogDueToCryticalError0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose days of week:.
        /// </summary>
        public static string ChooseDaysOfWeek {
            get {
                return ResourceManager.GetString("ChooseDaysOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the task you want to run:.
        /// </summary>
        public static string ChooseTheTaskYouWantToRun {
            get {
                return ResourceManager.GetString("ChooseTheTaskYouWantToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on item you want to restore and open context menu by right click.
        /// </summary>
        public static string ClickOnItemYouWantToRestoreAndOpenContextMenuByRightClick {
            get {
                return ResourceManager.GetString("ClickOnItemYouWantToRestoreAndOpenContextMenuByRightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit {0} to see command line arguments..
        /// </summary>
        public static string CommandLineArguments_Help {
            get {
                return ResourceManager.GetString("CommandLineArguments_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command line arguments..
        /// </summary>
        public static string CommandLineArguments_Invalid {
            get {
                return ResourceManager.GetString("CommandLineArguments_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue &gt;.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection script:.
        /// </summary>
        public static string DataStorage_Field_ConnectScript {
            get {
                return ResourceManager.GetString("DataStorage_Field_ConnectScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload limit, GB:.
        /// </summary>
        public static string DataStorage_Field_UploadQuota {
            get {
                return ResourceManager.GetString("DataStorage_Field_UploadQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits amount of data being sent during one task execution to storage. 0 - no limit.
        ///When quota is exceeded, other files will be skipped and will be processed next time.
        ///Usage scenario: You copy data to remote server. There&apos;s a problem: ISP drops upload speed after several gigabytes. This setting allows you to handle it..
        /// </summary>
        public static string DataStorage_Field_UploadQuota_Help {
            get {
                return ResourceManager.GetString("DataStorage_Field_UploadQuota_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If folder becomes available after executing some commands, specify PowerShell scripts for connection and disconnection..
        /// </summary>
        public static string DataStorage_Script_Help {
            get {
                return ResourceManager.GetString("DataStorage_Script_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage is not specified..
        /// </summary>
        public static string DataStorage_Validation_NotSpecified {
            get {
                return ResourceManager.GetString("DataStorage_Validation_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnection script:.
        /// </summary>
        public static string DataStorageStorage_Field_DisconnectionScript {
            get {
                return ResourceManager.GetString("DataStorageStorage_Field_DisconnectionScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Days_Friday {
            get {
                return ResourceManager.GetString("Days_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Days_Monday {
            get {
                return ResourceManager.GetString("Days_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Days_Saturday {
            get {
                return ResourceManager.GetString("Days_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Days_Sunday {
            get {
                return ResourceManager.GetString("Days_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Days_Thursday {
            get {
                return ResourceManager.GetString("Days_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Days_Tuesday {
            get {
                return ResourceManager.GetString("Days_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Days_Wednesday {
            get {
                return ResourceManager.GetString("Days_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete uncompleted backups from storage.
        /// </summary>
        public static string DeleteUnversionedFilesStorage {
            get {
                return ResourceManager.GetString("DeleteUnversionedFilesStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder:.
        /// </summary>
        public static string DestinationFolder {
            get {
                return ResourceManager.GetString("DestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder is not specified..
        /// </summary>
        public static string DestinationFolderIsNotSpecified {
            get {
                return ResourceManager.GetString("DestinationFolderIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop here files and folders which you&apos;re going to backup!.
        /// </summary>
        public static string DragAndDropHereFilesAndFoldersWhichYoureGoingToBackupForSettingCompressionPriorityUseMenu {
            get {
                return ResourceManager.GetString("DragAndDropHereFilesAndFoldersWhichYoureGoingToBackupForSettingCompressionPriorit" +
                        "yUseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit File Exclude Pattern....
        /// </summary>
        public static string EditFileExcludePattern {
            get {
                return ResourceManager.GetString("EditFileExcludePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed:.
        /// </summary>
        public static string Elapsed {
            get {
                return ResourceManager.GetString("Elapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption.
        /// </summary>
        public static string Encryption {
            get {
                return ResourceManager.GetString("Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - BUtil.
        /// </summary>
        public static string ErrorButil {
            get {
                return ResourceManager.GetString("ErrorButil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid command parameters specified!!!.
        /// </summary>
        public static string ErrorInvalidCommandParametersSpecified {
            get {
                return ResourceManager.GetString("ErrorInvalidCommandParametersSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder:.
        /// </summary>
        public static string Field_Folder {
            get {
                return ResourceManager.GetString("Field_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving files.
        /// </summary>
        public static string File_List_Saving {
            get {
                return ResourceManager.GetString("File_List_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving &quot;{0}&quot;.
        /// </summary>
        public static string File_Saving {
            get {
                return ResourceManager.GetString("File_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Exclusion Pattern:.
        /// </summary>
        public static string FileExclusionPattern {
            get {
                return ResourceManager.GetString("FileExclusionPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File globbing in .NET: Patterns.
        /// </summary>
        public static string FileGlobbingInNETPatterns {
            get {
                return ResourceManager.GetString("FileGlobbingInNETPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name transformations:.
        /// </summary>
        public static string FileNameTransformations {
            get {
                return ResourceManager.GetString("FileNameTransformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished succesfully.
        /// </summary>
        public static string FinishedSuccesfully {
            get {
                return ResourceManager.GetString("FinishedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished with errors.
        /// </summary>
        public static string FinishedWithErrors {
            get {
                return ResourceManager.GetString("FinishedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exist..
        /// </summary>
        public static string FolderDoesNotExist {
            get {
                return ResourceManager.GetString("FolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Storage....
        /// </summary>
        public static string FolderStorage {
            get {
                return ResourceManager.GetString("FolderStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage directory &quot;{0}&quot; was not found.
        ///
        ///Please update storage settings..
        /// </summary>
        public static string FolderStorageFailure {
            get {
                return ResourceManager.GetString("FolderStorageFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get state of file &quot;{0}&quot;.
        /// </summary>
        public static string GetStateOfFileFileName {
            get {
                return ResourceManager.GetString("GetStateOfFileFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get state of source item &quot;{0}&quot;.
        /// </summary>
        public static string GetStateOfSourceItem {
            get {
                return ResourceManager.GetString("GetStateOfSourceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get state of source items and storages.
        /// </summary>
        public static string GetStateOfSourceItemsAndStorages {
            get {
                return ResourceManager.GetString("GetStateOfSourceItemsAndStorages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get state of storage.
        /// </summary>
        public static string GetStateOfStorage {
            get {
                return ResourceManager.GetString("GetStateOfStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder storage....
        /// </summary>
        public static string HardDriveStorage {
            get {
                return ResourceManager.GetString("HardDriveStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported tokens:
        ///{DATE:Format} - Inserts file modification date in the specified format.
        ///To see all options google &quot;C# DateTime format&quot;..
        /// </summary>
        public static string HelpForTokens {
            get {
                return ResourceManager.GetString("HelpForTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can set up a scheduler. Shceduler can help you to automate creation of backups.
        /// </summary>
        public static string HereYouCanSetUpASchedulerShcedulerCanHelpYouToAutomateCreationOfBackups {
            get {
                return ResourceManager.GetString("HereYouCanSetUpASchedulerShcedulerCanHelpYouToAutomateCreationOfBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can specify file globbing exclusion patterns. 
        ///It can be a file name or folder name or wildcard. 
        ///Examples: 
        ///d:\temp, 
        ///d:\temp\file.txt, 
        ///d:\temp\**\*.txt or 
        ///bin. 
        ///See detailed description in the following link..
        /// </summary>
        public static string HereYouCanSpecifyFileGlobbingExclusionPatternsItCanBeAFileNameOrFolderNameOrWildcardExamplesDTempDTempFileTxtDTempTxtOrBinSeeDetailedDescriptionInTheFollowingLink {
            get {
                return ResourceManager.GetString("HereYouCanSpecifyFileGlobbingExclusionPatternsItCanBeAFileNameOrFolderNameOrWildc" +
                        "ardExamplesDTempDTempFileTxtDTempTxtOrBinSeeDetailedDescriptionInTheFollowingLin" +
                        "k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you may add folders and files you want to backup.
        /// </summary>
        public static string HereYouMayAddFoldersAndFilesYouWantToBackup {
            get {
                return ResourceManager.GetString("HereYouMayAddFoldersAndFilesYouWantToBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you choose something other than &apos;do nothing&apos; 
        ///program will configure OS to show you report
        ///on next your logon to the system if any errors 
        ///or warnings will be registered during the backup.
        /// </summary>
        public static string IfYouChooseSomethingOtherThanDoNothingNprogramWillConfigureOsToShowYouReportNonNextYourLogonToTheSystemIfAnyErrorsNorWarningsWillBeRegisteredDuringTheBackup {
            get {
                return ResourceManager.GetString("IfYouChooseSomethingOtherThanDoNothingNprogramWillConfigureOsToShowYouReportNonNe" +
                        "xtYourLogonToTheSystemIfAnyErrorsNorWarningsWillBeRegisteredDuringTheBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import &quot;{0}&quot;.
        /// </summary>
        public static string Import0 {
            get {
                return ResourceManager.GetString("Import0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import all files.
        /// </summary>
        public static string ImportAllFiles {
            get {
                return ResourceManager.GetString("ImportAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify data source.
        /// </summary>
        public static string ImportFilesFrom {
            get {
                return ResourceManager.GetString("ImportFilesFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create import media task.
        /// </summary>
        public static string ImportMediaTask_Create {
            get {
                return ResourceManager.GetString("ImportMediaTask_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &quot;{0}&quot; media import task.
        /// </summary>
        public static string ImportMediaTask_Edit_Title {
            get {
                return ResourceManager.GetString("ImportMediaTask_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports audios, photos, videos from SD Card of camera, recorder;
        ///photos and videos from your phone via WI-FI through FTP Server 
        ///application using template file names..
        /// </summary>
        public static string ImportMediaTask_Help {
            get {
                return ResourceManager.GetString("ImportMediaTask_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremental backup.
        /// </summary>
        public static string IncrementalBackup {
            get {
                return ResourceManager.GetString("IncrementalBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most basic form of incremental backup consists of identifying, recording and thus, preserving only those files that have changed since the last backup. Since changes are typically low, incremental backups are much smaller and quicker than full backups. For instance, following a full backup on Friday, a Monday backup will contain only those files that changed since Friday. A Tuesday backup contains only those files that changed since Monday, and so on. A full restoration of data will naturally be slower, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IncrementalBackupDescription {
            get {
                return ResourceManager.GetString("IncrementalBackupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information - BUtil.
        /// </summary>
        public static string InformationButil {
            get {
                return ResourceManager.GetString("InformationButil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrity verification script.ps1.
        /// </summary>
        public static string IntegrityVerificationScriptPs1 {
            get {
                return ResourceManager.GetString("IntegrityVerificationScriptPs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this place you can add locations where you would like your backup to be copied after completion of backup.
        /// </summary>
        public static string InThisPlaceYouCanAddLocationsWhereYouWouldLikeYourBackupToBeCopiedAfterCompletionOfBackup {
            get {
                return ResourceManager.GetString("InThisPlaceYouCanAddLocationsWhereYouWouldLikeYourBackupToBeCopiedAfterCompletion" +
                        "OfBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument(s) passed to the program.
        ///
        ///Please refer to manual for the complete list of parameters!.
        /// </summary>
        public static string InvalidArgumentSPassedToTheProgramNNpleaseReferToManualForTheCompleteListOfParameters {
            get {
                return ResourceManager.GetString("InvalidArgumentSPassedToTheProgramNNpleaseReferToManualForTheCompleteListOfParame" +
                        "ters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transform file name string..
        /// </summary>
        public static string InvalidTransformFileNameString {
            get {
                return ResourceManager.GetString("InvalidTransformFileNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to backup.
        /// </summary>
        public static string ItemsToBackup {
            get {
                return ResourceManager.GetString("ItemsToBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal: {0}.
        /// </summary>
        public static string Journal0 {
            get {
                return ResourceManager.GetString("Journal0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal for selected....
        /// </summary>
        public static string JournalSelected {
            get {
                return ResourceManager.GetString("JournalSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name_Field {
            get {
                return ResourceManager.GetString("Name_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is empty or contains not supported path characters..
        /// </summary>
        public static string Name_Field_Validation {
            get {
                return ResourceManager.GetString("Name_Field_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name_Title {
            get {
                return ResourceManager.GetString("Name_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network storages are not allowed to be pointed here!.
        /// </summary>
        public static string NetworkStoragesAreNotAllowedToBePointedHere {
            get {
                return ResourceManager.GetString("NetworkStoragesAreNotAllowedToBePointedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0} version is available.
        ///
        ///Changes are:
        ///{1}
        ///
        ///Program will now open browser with the download page.
        /// </summary>
        public static string New0VersionIsAvailableNNchangesAreN1NNprogramWillNowOpenBrowserWithTheDownloadPage {
            get {
                return ResourceManager.GetString("New0VersionIsAvailableNNchangesAreN1NNprogramWillNowOpenBrowserWithTheDownloadPag" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Explorer....
        /// </summary>
        public static string OpenInExplorer {
            get {
                return ResourceManager.GetString("OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open selected version....
        /// </summary>
        public static string OpenSelectedVersion {
            get {
                return ResourceManager.GetString("OpenSelectedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password_Field {
            get {
                return ResourceManager.GetString("Password_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        public static string Password_Field_Confirm {
            get {
                return ResourceManager.GetString("Password_Field_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        public static string Password_Field_Length {
            get {
                return ResourceManager.GetString("Password_Field_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string Password_Field_Validation_NotMatch {
            get {
                return ResourceManager.GetString("Password_Field_Validation_NotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not specified..
        /// </summary>
        public static string Password_Field_Validation_NotSpecified {
            get {
                return ResourceManager.GetString("Password_Field_Validation_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate password....
        /// </summary>
        public static string Password_Generate {
            get {
                return ResourceManager.GetString("Password_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password generator.
        /// </summary>
        public static string Password_Generator_Header {
            get {
                return ResourceManager.GetString("Password_Generator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (optional).
        /// </summary>
        public static string Password_Group_Header {
            get {
                return ResourceManager.GetString("Password_Group_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended minimum password length is 50 characters and more..
        /// </summary>
        public static string Password_Help {
            get {
                return ResourceManager.GetString("Password_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your backup is password protected, please type password here:.
        /// </summary>
        public static string Password_Recovery_Prompt {
            get {
                return ResourceManager.GetString("Password_Recovery_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Password_Use {
            get {
                return ResourceManager.GetString("Password_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern is empty..
        /// </summary>
        public static string PatternIsEmpty {
            get {
                return ResourceManager.GetString("PatternIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question - BUtil.
        /// </summary>
        public static string QuestionButil {
            get {
                return ResourceManager.GetString("QuestionButil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover!.
        /// </summary>
        public static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover selected....
        /// </summary>
        public static string RecoverSelected {
            get {
                return ResourceManager.GetString("RecoverSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration is completed..
        /// </summary>
        public static string RestorationIsCompleted {
            get {
                return ResourceManager.GetString("RestorationIsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration master.
        /// </summary>
        public static string RestorationMaster {
            get {
                return ResourceManager.GetString("RestorationMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Data....
        /// </summary>
        public static string RestoreData {
            get {
                return ResourceManager.GetString("RestoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name:.
        /// </summary>
        public static string Server_Field_Address {
            get {
                return ResourceManager.GetString("Server_Field_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name is not be specified..
        /// </summary>
        public static string Server_Field_Address_Validation {
            get {
                return ResourceManager.GetString("Server_Field_Address_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string Server_Field_Port {
            get {
                return ResourceManager.GetString("Server_Field_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port is invalid..
        /// </summary>
        public static string Server_Field_Port_Validation {
            get {
                return ResourceManager.GetString("Server_Field_Port_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share name is not specified..
        /// </summary>
        public static string ShareNameIsNotSpecified {
            get {
                return ResourceManager.GetString("ShareNameIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip already imported files.
        /// </summary>
        public static string SkipAlreadyImportedFiles {
            get {
                return ResourceManager.GetString("SkipAlreadyImportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files....
        /// </summary>
        public static string SourceItem_AddFiles {
            get {
                return ResourceManager.GetString("SourceItem_AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folders....
        /// </summary>
        public static string SourceItem_AddFolders {
            get {
                return ResourceManager.GetString("SourceItem_AddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items to backup!.
        /// </summary>
        public static string SourceItem_Validation_Empty {
            get {
                return ResourceManager.GetString("SourceItem_Validation_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; does not exist, correct list of source items..
        /// </summary>
        public static string SourceItem_Validation_NotExists {
            get {
                return ResourceManager.GetString("SourceItem_Validation_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source item &quot;{0}&quot; does not exist.
        ///
        ///Please correct list of source items..
        /// </summary>
        public static string SourceItemFailure {
            get {
                return ResourceManager.GetString("SourceItemFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the folder where to store back-up:.
        /// </summary>
        public static string SpecifyTheFolderWhereToStoreBackUp {
            get {
                return ResourceManager.GetString("SpecifyTheFolderWhereToStoreBackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing state.
        /// </summary>
        public static string State_Saving {
            get {
                return ResourceManager.GetString("State_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add exclude file pattern.
        /// </summary>
        public static string StorageItem_ExcludePattern_Add {
            get {
                return ResourceManager.GetString("StorageItem_ExcludePattern_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip processing files by pattern..
        /// </summary>
        public static string StorageItem_ExcludePattern_Hint {
            get {
                return ResourceManager.GetString("StorageItem_ExcludePattern_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Task_Create {
            get {
                return ResourceManager.GetString("Task_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates new task..
        /// </summary>
        public static string Task_Create_Hint {
            get {
                return ResourceManager.GetString("Task_Create_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Task_Delete {
            get {
                return ResourceManager.GetString("Task_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete &quot;{0}&quot;?.
        /// </summary>
        public static string Task_Delete_Confirm {
            get {
                return ResourceManager.GetString("Task_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the selected task..
        /// </summary>
        public static string Task_Delete_Hint {
            get {
                return ResourceManager.GetString("Task_Delete_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Task_Edit {
            get {
                return ResourceManager.GetString("Task_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edits the selected task..
        /// </summary>
        public static string Task_Edit_Hint {
            get {
                return ResourceManager.GetString("Task_Edit_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot edit this type of task in CLI..
        /// </summary>
        public static string Task_Edit_Validation_NoCLI {
            get {
                return ResourceManager.GetString("Task_Edit_Validation_NoCLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task.
        /// </summary>
        public static string Task_Field_Name_NewDefaultValue {
            get {
                return ResourceManager.GetString("Task_Field_Name_NewDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Task_LastBackup {
            get {
                return ResourceManager.GetString("Task_LastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Task_Launch {
            get {
                return ResourceManager.GetString("Task_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launches selected task..
        /// </summary>
        public static string Task_Launch_Hint {
            get {
                return ResourceManager.GetString("Task_Launch_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Task_List {
            get {
                return ResourceManager.GetString("Task_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed (see opened log).
        /// </summary>
        public static string Task_Status_FailedSeeLog {
            get {
                return ResourceManager.GetString("Task_Status_FailedSeeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task is in a progress... .
        /// </summary>
        public static string Task_Status_InProgress {
            get {
                return ResourceManager.GetString("Task_Status_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfull.
        /// </summary>
        public static string Task_Status_Succesfull {
            get {
                return ResourceManager.GetString("Task_Status_Succesfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &apos;{0}&apos; wasn&apos;t found..
        /// </summary>
        public static string Task_Validation_NotFound {
            get {
                return ResourceManager.GetString("Task_Validation_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task type is not supported..
        /// </summary>
        public static string Task_Validation_NotSupported {
            get {
                return ResourceManager.GetString("Task_Validation_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task finished succesfully!.
        /// </summary>
        public static string TaskFinishedSuccesfully {
            get {
                return ResourceManager.GetString("TaskFinishedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has failed (see opened log).
        /// </summary>
        public static string TaskHasFailedSeeOpenedLog {
            get {
                return ResourceManager.GetString("TaskHasFailedSeeOpenedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task is succeeded!.
        /// </summary>
        public static string TaskIsSucceeded {
            get {
                return ResourceManager.GetString("TaskIsSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items to backup!
        ///
        ///You can specify the data to backup in Configurator in &apos;What&apos; settings group..
        /// </summary>
        public static string ThereAreNoItemsToBackupNNyouCanSpecifyTheDataToBackupInConfiguratorInWhatSettingsGroup {
            get {
                return ResourceManager.GetString("ThereAreNoItemsToBackupNNyouCanSpecifyTheDataToBackupInConfiguratorInWhatSettings" +
                        "Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour:.
        /// </summary>
        public static string Time_Field_Hour {
            get {
                return ResourceManager.GetString("Time_Field_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute:.
        /// </summary>
        public static string Time_Field_Minute {
            get {
                return ResourceManager.GetString("Time_Field_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform file name is empty..
        /// </summary>
        public static string TransformFileNameIsEmpty {
            get {
                return ResourceManager.GetString("TransformFileNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url:.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string User_Field {
            get {
                return ResourceManager.GetString("User_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not specified..
        /// </summary>
        public static string User_Field_Validation {
            get {
                return ResourceManager.GetString("User_Field_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What?.
        /// </summary>
        public static string What {
            get {
                return ResourceManager.GetString("What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When?.
        /// </summary>
        public static string When {
            get {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where?.
        /// </summary>
        public static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you lile to remove the backup task &apos;{0}&apos; ?.
        /// </summary>
        public static string WouldYouLileToRemoveTheBackupTask0 {
            get {
                return ResourceManager.GetString("WouldYouLileToRemoveTheBackupTask0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write incremented version to storage.
        /// </summary>
        public static string WriteIncrementedVersionToStorage {
            get {
                return ResourceManager.GetString("WriteIncrementedVersionToStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write integrity verification scripts.
        /// </summary>
        public static string WriteIntegrityVerificationScriptsToStorage {
            get {
                return ResourceManager.GetString("WriteIntegrityVerificationScriptsToStorage", resourceCulture);
            }
        }
    }
}
