//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUtil.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUtil.Core.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After backup task: .
        /// </summary>
        public static string AfterBackupTask {
            get {
                return ResourceManager.GetString("AfterBackupTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured
        ///
        ///Please contact the developers with information saved on your desktop in
        ///&quot;{0}&quot;
        ///
        ///Application will now close.
        /// </summary>
        public static string AnUnexpectedErrorOccuredNNpleaseContactTheDevelopersWithInformationSavedOnYourDesktopInN0NNapplicationWillNowClose {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccuredNNpleaseContactTheDevelopersWithInformationSavedOnYourDes" +
                        "ktopInN0NNapplicationWillNowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup finished succesfully!.
        /// </summary>
        public static string BackupFinishedSuccesfully {
            get {
                return ResourceManager.GetString("BackupFinishedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Report.
        /// </summary>
        public static string BackupReport {
            get {
                return ResourceManager.GetString("BackupReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup was partial. Due to storage quota some files were not copied. Remaining {0} files with of {1} GB..
        /// </summary>
        public static string BackupWasPartialDueToStorageQuota {
            get {
                return ResourceManager.GetString("BackupWasPartialDueToStorageQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before backup task: .
        /// </summary>
        public static string BeforeBackupTask {
            get {
                return ResourceManager.GetString("BeforeBackupTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate incremented version.
        /// </summary>
        public static string CalculateIncrementedVersionForStorage {
            get {
                return ResourceManager.GetString("CalculateIncrementedVersionForStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation is not equal to password.
        /// </summary>
        public static string ConfirmationIsNotEqualToPassword {
            get {
                return ResourceManager.GetString("ConfirmationIsNotEqualToPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying file &apos;{0}&apos; from temp folder &apos;{1}&apos; to destination &apos;{2}&apos; at {3}.
        /// </summary>
        public static string CopyingFile0FromTempFolder1ToDestination2At3 {
            get {
                return ResourceManager.GetString("CopyingFile0FromTempFolder1ToDestination2At3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying of backup to &apos;{0}&apos; network storage skipped because its size {1} exceeded specified limit {2}.
        /// </summary>
        public static string CopyingOfBackupTo0NetworkStorageSkippedBecauseItsSize1ExceededSpecifiedLimit2 {
            get {
                return ResourceManager.GetString("CopyingOfBackupTo0NetworkStorageSkippedBecauseItsSize1ExceededSpecifiedLimit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy to clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not kill process &apos;{0}&apos;: {1}.
        /// </summary>
        public static string CouldNotKillProcess01 {
            get {
                return ResourceManager.GetString("CouldNotKillProcess01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start packer due to {0}. Aborting backup....
        /// </summary>
        public static string CouldNotStartPackerDueTo0AbortingBackup {
            get {
                return ResourceManager.GetString("CouldNotStartPackerDueTo0AbortingBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start process &apos;{0}&apos;: {1}.
        /// </summary>
        public static string CouldNotStartProcess01 {
            get {
                return ResourceManager.GetString("CouldNotStartProcess01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete uncompleted backups from storage.
        /// </summary>
        public static string DeleteUnversionedFilesStorage {
            get {
                return ResourceManager.GetString("DeleteUnversionedFilesStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password:.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Succesfully.
        /// </summary>
        public static string FinishedSuccesfully {
            get {
                return ResourceManager.GetString("FinishedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished With Errors.
        /// </summary>
        public static string FinishedWithErrors {
            get {
                return ResourceManager.GetString("FinishedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage directory &quot;{0}&quot; was not found.
        ///
        ///Please update storage settings..
        /// </summary>
        public static string FolderStorageFailure {
            get {
                return ResourceManager.GetString("FolderStorageFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new random password.
        /// </summary>
        public static string GenerateNewRandomPassword {
            get {
                return ResourceManager.GetString("GenerateNewRandomPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get state of file &quot;{0}&quot;.
        /// </summary>
        public static string GetStateOfFileFileName {
            get {
                return ResourceManager.GetString("GetStateOfFileFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get state of source item &quot;{0}&quot;.
        /// </summary>
        public static string GetStateOfSourceItem {
            get {
                return ResourceManager.GetString("GetStateOfSourceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get state of source items and storages.
        /// </summary>
        public static string GetStateOfSourceItemsAndStorages {
            get {
                return ResourceManager.GetString("GetStateOfSourceItemsAndStorages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get state of storage.
        /// </summary>
        public static string GetStateOfStorage {
            get {
                return ResourceManager.GetString("GetStateOfStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Here is your password&gt;.
        /// </summary>
        public static string HereIsYourPassword {
            get {
                return ResourceManager.GetString("HereIsYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremental Backup.
        /// </summary>
        public static string IncrementalBackup {
            get {
                return ResourceManager.GetString("IncrementalBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress....
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrity verification script.ps1.
        /// </summary>
        public static string IntegrityVerificationScriptPs1 {
            get {
                return ResourceManager.GetString("IntegrityVerificationScriptPs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrity verification script.sh.
        /// </summary>
        public static string IntegrityVerificationScriptSh {
            get {
                return ResourceManager.GetString("IntegrityVerificationScriptSh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is a backup tool for running on computer. For more information see Manual.
        /// </summary>
        public static string IsABackupToolForRunningOnComputerForMoreInformationSeeManual {
            get {
                return ResourceManager.GetString("IsABackupToolForRunningOnComputerForMoreInformationSeeManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localization options are not setted.
        /// </summary>
        public static string LocalizationOptionsAreNotSetted {
            get {
                return ResourceManager.GetString("LocalizationOptionsAreNotSetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Password length should be more than 20 characters and less than 257 characters
        ///.
        /// </summary>
        public static string NotePasswordLengthShouldBeMoreThan20CharactersAndLessThan257CharactersRN {
            get {
                return ResourceManager.GetString("NotePasswordLengthShouldBeMoreThan20CharactersAndLessThan257CharactersRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing data in an image.
        /// </summary>
        public static string PackingDataInAnImage {
            get {
                return ResourceManager.GetString("PackingDataInAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password generator.
        /// </summary>
        public static string PasswordGenerator {
            get {
                return ResourceManager.GetString("PasswordGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (if needed).
        /// </summary>
        public static string PasswordIfNeeded {
            get {
                return ResourceManager.GetString("PasswordIfNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid.
        ///
        ///It was reseted
        ///.
        /// </summary>
        public static string PasswordIsInvalidNNitWasResetedN {
            get {
                return ResourceManager.GetString("PasswordIsInvalidNNitWasResetedN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length:.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7z message:.
        /// </summary>
        public static string SevenZMessage {
            get {
                return ResourceManager.GetString("SevenZMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit project homepage.
        /// </summary>
        public static string VisitProjectHomepage {
            get {
                return ResourceManager.GetString("VisitProjectHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write incremented version to storage.
        /// </summary>
        public static string WriteIncrementedVersionToStorage {
            get {
                return ResourceManager.GetString("WriteIncrementedVersionToStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write integrity verification scripts.
        /// </summary>
        public static string WriteIntegrityVerificationScriptsToStorage {
            get {
                return ResourceManager.GetString("WriteIntegrityVerificationScriptsToStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write files to storage.
        /// </summary>
        public static string WriteSourceFilesToStorage {
            get {
                return ResourceManager.GetString("WriteSourceFilesToStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write file &quot;{0}&quot;.
        /// </summary>
        public static string WriteSourceFileToStorage {
            get {
                return ResourceManager.GetString("WriteSourceFileToStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write state.
        /// </summary>
        public static string WriteStateToStorage {
            get {
                return ResourceManager.GetString("WriteStateToStorage", resourceCulture);
            }
        }
    }
}
