
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.24.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace BUtil.ConsoleBackup.UI {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyView : Terminal.Gui.Toplevel
    {
        
        private Terminal.Gui.StatusBar statusBar;
        
        private Terminal.Gui.StatusItem f1EditMe;
        
        private Terminal.Gui.MenuBar menuBar;
        
        private Terminal.Gui.MenuBarItem runF5Menu;
        
        private Terminal.Gui.MenuItem editMeMenuItem;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.MenuBar();
            this.statusBar = new Terminal.Gui.StatusBar();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.statusBar.Width = Dim.Fill(0);
            this.statusBar.Height = 1;
            this.statusBar.X = 1;
            this.statusBar.Y = Pos.AnchorEnd(1);
            this.statusBar.Data = "statusBar";
            this.statusBar.Text = "Run (F5)";
            this.statusBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.f1EditMe = new Terminal.Gui.StatusItem(((Terminal.Gui.Key)(1048588u)), "F1 - Edit Me", null);
            this.statusBar.Items = new Terminal.Gui.StatusItem[] {
                    this.f1EditMe};
            this.Add(this.statusBar);
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 1;
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.runF5Menu = new Terminal.Gui.MenuBarItem();
            this.runF5Menu.Title = "_Run (F5)";
            this.editMeMenuItem = new Terminal.Gui.MenuItem();
            this.editMeMenuItem.Title = "Edit Me";
            this.editMeMenuItem.Data = "editMeMenuItem";
            this.runF5Menu.Children = new Terminal.Gui.MenuItem[] {
                    this.editMeMenuItem};
            this.menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.runF5Menu};
            this.Add(this.menuBar);
        }
    }
}
