//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUtil.ConsoleBackup.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUtil.ConsoleBackup.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Create.
        /// </summary>
        internal static string _Create {
            get {
                return ResourceManager.GetString("_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete (F8, Del).
        /// </summary>
        internal static string _DeleteF8Del {
            get {
                return ResourceManager.GetString("_DeleteF8Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit (F4).
        /// </summary>
        internal static string _EditF4 {
            get {
                return ResourceManager.GetString("_EditF4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Run (F5, Enter).
        /// </summary>
        internal static string _RunF5Enter {
            get {
                return ResourceManager.GetString("_RunF5Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file log due to crytical error {0}.
        /// </summary>
        internal static string CannotOpenFileLogDueToCryticalError0 {
            get {
                return ResourceManager.GetString("CannotOpenFileLogDueToCryticalError0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Photos/Videos moval task.
        /// </summary>
        internal static string CreatePhotosVideosMovalTask {
            get {
                return ResourceManager.GetString("CreatePhotosVideosMovalTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination directory does not exist..
        /// </summary>
        internal static string DestinationDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DestinationDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder:.
        /// </summary>
        internal static string DestinationFolder {
            get {
                return ResourceManager.GetString("DestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid command parameters specified!!!.
        /// </summary>
        internal static string ErrorInvalidCommandParametersSpecified {
            get {
                return ResourceManager.GetString("ErrorInvalidCommandParametersSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name transformations:.
        /// </summary>
        internal static string FileNameTransformations {
            get {
                return ResourceManager.GetString("FileNameTransformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder:.
        /// </summary>
        internal static string FolderField {
            get {
                return ResourceManager.GetString("FolderField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported tokens:
        ///{DATE:Format} - Inserts file modification date in the specified format.
        ///To see all options google &quot;C# DateTime format&quot;..
        /// </summary>
        internal static string HelpForTokens {
            get {
                return ResourceManager.GetString("HelpForTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host:.
        /// </summary>
        internal static string HostField {
            get {
                return ResourceManager.GetString("HostField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string PasswordField {
            get {
                return ResourceManager.GetString("PasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos/Videos location on media device.
        /// </summary>
        internal static string PhotosVideosFolderOnMediaDevice {
            get {
                return ResourceManager.GetString("PhotosVideosFolderOnMediaDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &quot;{0}&quot; Photos/Videos moval task.
        /// </summary>
        internal static string PhotosVideosMovalTask {
            get {
                return ResourceManager.GetString("PhotosVideosMovalTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm deletion of &quot;{0}&quot;.
        /// </summary>
        internal static string PleaseConfirmDeletionOf0 {
            get {
                return ResourceManager.GetString("PleaseConfirmDeletionOf0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, specify the backup task title using the command line argument &quot;{0}My backup task title&quot;
        ///Example: butilc.exe &quot;{0}My backup title&quot;.
        /// </summary>
        internal static string PleaseSpecifyTheBackupTaskTitleUsingTheCommandLineArgument0MyBackupTaskTitleNexampleBackupExe0MyBackupTitle {
            get {
                return ResourceManager.GetString("PleaseSpecifyTheBackupTaskTitleUsingTheCommandLineArgument0MyBackupTaskTitleNexam" +
                        "pleBackupExe0MyBackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string PortField {
            get {
                return ResourceManager.GetString("PortField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo/Video location was not specified..
        /// </summary>
        internal static string SourceFolderDoesNotExist {
            get {
                return ResourceManager.GetString("SourceFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify location.
        /// </summary>
        internal static string SpecifyLocation {
            get {
                return ResourceManager.GetString("SpecifyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has failed (see opened log).
        /// </summary>
        internal static string TaskHasFailedSeeOpenedLog {
            get {
                return ResourceManager.GetString("TaskHasFailedSeeOpenedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task is succeeded!.
        /// </summary>
        internal static string TaskIsSucceeded {
            get {
                return ResourceManager.GetString("TaskIsSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задания.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;re no backup task with title &apos;{0}&apos;..
        /// </summary>
        internal static string TherereNoBackupTaskWithTitle0 {
            get {
                return ResourceManager.GetString("TherereNoBackupTaskWithTitle0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is empty or contains not supported path characters..
        /// </summary>
        internal static string TitleIsEmptyOrContainsNotSupportedPathCharacters {
            get {
                return ResourceManager.GetString("TitleIsEmptyOrContainsNotSupportedPathCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To run program with this switch you should disable scheduling in options first. Please refer to manual!.
        /// </summary>
        internal static string ToRunProgramWithThisSwitchYouShouldDisableSchedulingInOptionsFirstPleaseReferToManual {
            get {
                return ResourceManager.GetString("ToRunProgramWithThisSwitchYouShouldDisableSchedulingInOptionsFirstPleaseReferToMa" +
                        "nual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform file name is empty..
        /// </summary>
        internal static string TransformFileNameIsEmpty {
            get {
                return ResourceManager.GetString("TransformFileNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage variants:
        ///
        ///butilc.exe &quot;Task=My task title&quot;
        ///   Runs specified task.
        ///
        ///butilc.exe &quot;Task=My task title&quot; Shutdown
        ///butilc.exe &quot;Task=My task title&quot; LogOff 
        ///butilc.exe &quot;Task=My task title&quot; Reboot
        ///
        ///butilc.exe Help
        ///   Outputs brief help
        ///.
        /// </summary>
        internal static string UsageVariantsNNbackupExeTaskMyTaskTitleNRunningWithoutParametersOutputsInformationToConsoleNNbackupExeTaskMyTask1TitleTaskMyTask2TitleTaskMyTask3TitleNRunsSeveralTasksOneByOneNNbackupExeTaskMyTaskTitleUsefilelogNOutputsInformationInFileLogNNbackupExeTaskMyTaskTitleShutdownNbackupExeTaskMyTaskTitleLogoffNbackupExeTaskMyTaskTitleSuspendNbackupExeTaskMyTaskTitleRebootNbackupExeTaskMyTaskTitleHibernateNNbackupExeHelpNOutputsBriefHelpN {
            get {
                return ResourceManager.GetString(@"UsageVariantsNNbackupExeTaskMyTaskTitleNRunningWithoutParametersOutputsInformationToConsoleNNbackupExeTaskMyTask1TitleTaskMyTask2TitleTaskMyTask3TitleNRunsSeveralTasksOneByOneNNbackupExeTaskMyTaskTitleUsefilelogNOutputsInformationInFileLogNNbackupExeTaskMyTaskTitleShutdownNbackupExeTaskMyTaskTitleLogoffNbackupExeTaskMyTaskTitleSuspendNbackupExeTaskMyTaskTitleRebootNbackupExeTaskMyTaskTitleHibernateNNbackupExeHelpNOutputsBriefHelpN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        internal static string UserField {
            get {
                return ResourceManager.GetString("UserField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot edit this type of task in CLI..
        /// </summary>
        internal static string YouCannotEditThisTypeOfTaskInCLI {
            get {
                return ResourceManager.GetString("YouCannotEditThisTypeOfTaskInCLI", resourceCulture);
            }
        }
    }
}
