//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUtil.Configurator.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUtil.Configurator.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day(s) {1} h : {2} min : {3} sec.
        /// </summary>
        internal static string _0DayS1H2Min3Sec {
            get {
                return ResourceManager.GetString("_0DayS1H2Min3Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} h : {1} min : {2} sec.
        /// </summary>
        internal static string _0H1Min2Sec {
            get {
                return ResourceManager.GetString("_0H1Min2Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min : {1} sec.
        /// </summary>
        internal static string _0Min1Sec {
            get {
                return ResourceManager.GetString("_0Min1Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sec.
        /// </summary>
        internal static string _0Sec {
            get {
                return ResourceManager.GetString("_0Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Backup should be password protected. If NOT, program will SKIP its copying to this storage
        ///2. Your authorization information is going over the network in UNPROTECTED mode(as plain text)..
        /// </summary>
        internal static string _1BackupShouldBePasswordProtectedIfNotProgramWillSkipItsCopyingToThisStorageN2YourAuthorizationInformationIsGoingOverTheNetworkInUnprotectedModeAsPlainText {
            get {
                return ResourceManager.GetString("_1BackupShouldBePasswordProtectedIfNotProgramWillSkipItsCopyingToThisStorageN2You" +
                        "rAuthorizationInformationIsGoingOverTheNetworkInUnprotectedModeAsPlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above normal.
        /// </summary>
        internal static string AboveNormal {
            get {
                return ResourceManager.GetString("AboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files....
        /// </summary>
        internal static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folders....
        /// </summary>
        internal static string AddFolders {
            get {
                return ResourceManager.GetString("AddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional encryption under your local system account. 
        ///Requires NTFS file system and win2k OS on remote machine. Backup data will be available only for your OS account. See documentation for details.
        /// </summary>
        internal static string AdditionalEncryptionUnderYourLocalSystemAccountNrequiresNtfsFileSystemAndWin2kOsOnRemoteMachineBackupDataWillBeAvailableOnlyForYourOsAccountSeeDocumentationForDetails {
            get {
                return ResourceManager.GetString("AdditionalEncryptionUnderYourLocalSystemAccountNrequiresNtfsFileSystemAndWin2kOsO" +
                        "nRemoteMachineBackupDataWillBeAvailableOnlyForYourOsAccountSeeDocumentationForDe" +
                        "tails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds the new backup task....
        /// </summary>
        internal static string AddsTheNewBackupTask {
            get {
                return ResourceManager.GetString("AddsTheNewBackupTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After completion of backup.
        /// </summary>
        internal static string AfterCompletionOfBackup {
            get {
                return ResourceManager.GetString("AfterCompletionOfBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of 7-zip processes to run synchronously:.
        /// </summary>
        internal static string AmountOf7ZipProcessesToRunSynchronously {
            get {
                return ResourceManager.GetString("AmountOf7ZipProcessesToRunSynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of storages to process synchronously:.
        /// </summary>
        internal static string AmountOfStoragesToProcessSynchronously {
            get {
                return ResourceManager.GetString("AmountOfStoragesToProcessSynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization information.
        /// </summary>
        internal static string AuthorizationInformation {
            get {
                return ResourceManager.GetString("AuthorizationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup data every....
        /// </summary>
        internal static string BackupDataEvery {
            get {
                return ResourceManager.GetString("BackupDataEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup failed.
        ///
        ///Please review opened log..
        /// </summary>
        internal static string BackupFailedPleaseReviewOpenedLog {
            get {
                return ResourceManager.GetString("BackupFailedPleaseReviewOpenedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup is in a progress... .
        /// </summary>
        internal static string BackupIsInAProgress {
            get {
                return ResourceManager.GetString("BackupIsInAProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup is in progress....
        /// </summary>
        internal static string BackupIsInProgress {
            get {
                return ResourceManager.GetString("BackupIsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup journals.
        /// </summary>
        internal static string BackupJournals {
            get {
                return ResourceManager.GetString("BackupJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup process completed succesfully!!!.
        /// </summary>
        internal static string BackupProcessCompletedSuccesfully {
            get {
                return ResourceManager.GetString("BackupProcessCompletedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Task &apos;{0}&apos;.
        /// </summary>
        internal static string BackupTask0 {
            get {
                return ResourceManager.GetString("BackupTask0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup tasks.
        /// </summary>
        internal static string BackupTasks {
            get {
                return ResourceManager.GetString("BackupTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beep several times.
        /// </summary>
        internal static string BeepSeveralTimes {
            get {
                return ResourceManager.GetString("BeepSeveralTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below normal.
        /// </summary>
        internal static string BelowNormal {
            get {
                return ResourceManager.GetString("BelowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUG REPORT.
        /// </summary>
        internal static string BugReport {
            get {
                return ResourceManager.GetString("BugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUtil software package component &apos;{0}&apos; is missing.
        ///
        ///Please reinstall application.
        ///
        ///Restoration, Backup and Help functions will be unavailable..
        /// </summary>
        internal static string ButilSoftwarePackageComponent0IsMissingNNpleaseReinstallApplicationNNrestorationBackupAndHelpFunctionsWillBeUnavailable {
            get {
                return ResourceManager.GetString("ButilSoftwarePackageComponent0IsMissingNNpleaseReinstallApplicationNNrestorationB" +
                        "ackupAndHelpFunctionsWillBeUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute required manipulations with server
        ///.
        /// </summary>
        internal static string CannotExecuteRequiredManipulationsWithServerN {
            get {
                return ResourceManager.GetString("CannotExecuteRequiredManipulationsWithServerN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run 7zg.exe because {0}.
        /// </summary>
        internal static string CannotRun7ZgExeBecause0 {
            get {
                return ResourceManager.GetString("CannotRun7ZgExeBecause0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute AFTER backup.
        /// </summary>
        internal static string ChainOfProgramsToExecuteAfterBackup {
            get {
                return ResourceManager.GetString("ChainOfProgramsToExecuteAfterBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute BEFORE backup.
        /// </summary>
        internal static string ChainOfProgramsToExecuteBeforeBackup {
            get {
                return ResourceManager.GetString("ChainOfProgramsToExecuteBeforeBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Change logs location.
        /// </summary>
        internal static string ChangeLogsLocation {
            get {
                return ResourceManager.GetString("ChangeLogsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates....
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose backup model.
        /// </summary>
        internal static string ChooseBackupModel {
            get {
                return ResourceManager.GetString("ChooseBackupModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose backup priority:.
        /// </summary>
        internal static string ChooseBackupPriority {
            get {
                return ResourceManager.GetString("ChooseBackupPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose days of week:.
        /// </summary>
        internal static string ChooseDaysOfWeek {
            get {
                return ResourceManager.GetString("ChooseDaysOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose logging level:.
        /// </summary>
        internal static string ChooseLoggingLevel {
            get {
                return ResourceManager.GetString("ChooseLoggingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the task you want to run:.
        /// </summary>
        internal static string ChooseTheTaskYouWantToRun {
            get {
                return ResourceManager.GetString("ChooseTheTaskYouWantToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line arguments:.
        /// </summary>
        internal static string CommandLineArguments {
            get {
                return ResourceManager.GetString("CommandLineArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurator.
        /// </summary>
        internal static string Configurator {
            get {
                return ResourceManager.GetString("Configurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue &gt;.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not continue work after getting options because {0}.
        /// </summary>
        internal static string CouldNotContinueWorkAfterGettingOptionsBecause0 {
            get {
                return ResourceManager.GetString("CouldNotContinueWorkAfterGettingOptionsBecause0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data transfer mode:.
        /// </summary>
        internal static string DataTransferMode {
            get {
                return ResourceManager.GetString("DataTransferMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %  (default is 60).
        /// </summary>
        internal static string DefaultIs60 {
            get {
                return ResourceManager.GetString("DefaultIs60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder.
        /// </summary>
        internal static string DestinationFolder {
            get {
                return ResourceManager.GetString("DestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder does not exist..
        /// </summary>
        internal static string DestinationFolderDoesNotExist {
            get {
                return ResourceManager.GetString("DestinationFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable compression and encryption.
        /// </summary>
        internal static string DisableCompressionAndEncryption {
            get {
                return ResourceManager.GetString("DisableCompressionAndEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling compression and encryption is designed for the following usages:
        ///a) storing information on drives protected by BitLocker (BitLocker requires Professional Windows Edition) or protected by encrypted proxy file system software like encryptfs. On NTFS file system you can enable compression.
        ///b) storing information on a cloud FTP, SFTP, WebDAV, Amazon S3, OpenStack Swift, Backblaze B2, Microsoft Azure &amp; OneDrive, Google Drive, and Dropbox by encrypted proxy file system Cryptomator/CyberDuck. Mounting  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DisableCompressionAndEncryptionDescription {
            get {
                return ResourceManager.GetString("DisableCompressionAndEncryptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dns name or IP: ftp://.
        /// </summary>
        internal static string DnsNameOrIpFtp {
            get {
                return ResourceManager.GetString("DnsNameOrIpFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        internal static string DoNothing {
            get {
                return ResourceManager.GetString("DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to stop backup process?.
        /// </summary>
        internal static string DoYouReallyWantToStopBackupProcess {
            get {
                return ResourceManager.GetString("DoYouReallyWantToStopBackupProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop here files and folders which you&apos;re going to backup!.
        /// </summary>
        internal static string DragAndDropHereFilesAndFoldersWhichYoureGoingToBackupForSettingCompressionPriorityUseMenu {
            get {
                return ResourceManager.GetString("DragAndDropHereFilesAndFoldersWhichYoureGoingToBackupForSettingCompressionPriorit" +
                        "yUseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing Event Task - Configurator.
        /// </summary>
        internal static string EditingEventTaskConfigurator {
            get {
                return ResourceManager.GetString("EditingEventTaskConfigurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edits the selected backup task....
        /// </summary>
        internal static string EditsTheSelectedBackupTask {
            get {
                return ResourceManager.GetString("EditsTheSelectedBackupTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed:.
        /// </summary>
        internal static string Elapsed {
            get {
                return ResourceManager.GetString("Elapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption.
        /// </summary>
        internal static string Encryption {
            get {
                return ResourceManager.GetString("Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erroneous.
        /// </summary>
        internal static string Erroneous {
            get {
                return ResourceManager.GetString("Erroneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors and warnings will be saved in logs.
        /// </summary>
        internal static string ErrorsAndWarningsWillBeSavedInLogs {
            get {
                return ResourceManager.GetString("ErrorsAndWarningsWillBeSavedInLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting....
        /// </summary>
        internal static string Exiting {
            get {
                return ResourceManager.GetString("Exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Succesfully.
        /// </summary>
        internal static string FinishedSuccesfully {
            get {
                return ResourceManager.GetString("FinishedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished With Errors.
        /// </summary>
        internal static string FinishedWithErrors {
            get {
                return ResourceManager.GetString("FinishedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP.
        /// </summary>
        internal static string Ftp {
            get {
                return ResourceManager.GetString("Ftp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP server.
        /// </summary>
        internal static string FtpServer {
            get {
                return ResourceManager.GetString("FtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ftp storage....
        /// </summary>
        internal static string FtpStorage {
            get {
                return ResourceManager.GetString("FtpStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP Storage Configuration.
        /// </summary>
        internal static string FtpStorageConfiguration {
            get {
                return ResourceManager.GetString("FtpStorageConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate password....
        /// </summary>
        internal static string GeneratePassword {
            get {
                return ResourceManager.GetString("GeneratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard drive storage....
        /// </summary>
        internal static string HardDriveStorage {
            get {
                return ResourceManager.GetString("HardDriveStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDD.
        /// </summary>
        internal static string Hdd {
            get {
                return ResourceManager.GetString("Hdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDD Storage Configuration.
        /// </summary>
        internal static string HddStorageConfiguration {
            get {
                return ResourceManager.GetString("HddStorageConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can protect the backup with password (this is also required for copying it over network).
        /// </summary>
        internal static string HereYouCanProtectTheBackupWithPasswordThisIsAlsoRequiredForCopyingItOverNetwork {
            get {
                return ResourceManager.GetString("HereYouCanProtectTheBackupWithPasswordThisIsAlsoRequiredForCopyingItOverNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can set up a scheduler. Shceduler can help you to automate creation of backups.
        /// </summary>
        internal static string HereYouCanSetUpASchedulerShcedulerCanHelpYouToAutomateCreationOfBackups {
            get {
                return ResourceManager.GetString("HereYouCanSetUpASchedulerShcedulerCanHelpYouToAutomateCreationOfBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can set up logging properties.
        /// </summary>
        internal static string HereYouCanSetUpLoggingProperties {
            get {
                return ResourceManager.GetString("HereYouCanSetUpLoggingProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can specify other settings.
        /// </summary>
        internal static string HereYouCanSpecifyOtherSettings {
            get {
                return ResourceManager.GetString("HereYouCanSpecifyOtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can specify where to send backups.
        /// </summary>
        internal static string HereYouCanSpecifyWhereToSendBackups {
            get {
                return ResourceManager.GetString("HereYouCanSpecifyWhereToSendBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you may add files and folders you wanna to backup.
        /// </summary>
        internal static string HereYouMayAddFilesAndFoldersYouWannaToBackup {
            get {
                return ResourceManager.GetString("HereYouMayAddFilesAndFoldersYouWannaToBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you may add folders and files you want to backup.
        /// </summary>
        internal static string HereYouMayAddFoldersAndFilesYouWantToBackup {
            get {
                return ResourceManager.GetString("HereYouMayAddFoldersAndFilesYouWantToBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate PC.
        /// </summary>
        internal static string HibernatePc {
            get {
                return ResourceManager.GetString("HibernatePc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour:.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How ?.
        /// </summary>
        internal static string How {
            get {
                return ResourceManager.GetString("How", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can specify the backup model that will be used for compression..
        /// </summary>
        internal static string HowHint {
            get {
                return ResourceManager.GetString("HowHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you choose something other than &apos;do nothing&apos; 
        ///program will configure OS to show you report
        ///on next your logon to the system if any errors 
        ///or warnings will be registered during the backup.
        /// </summary>
        internal static string IfYouChooseSomethingOtherThanDoNothingNprogramWillConfigureOsToShowYouReportNonNextYourLogonToTheSystemIfAnyErrorsNorWarningsWillBeRegisteredDuringTheBackup {
            get {
                return ResourceManager.GetString("IfYouChooseSomethingOtherThanDoNothingNprogramWillConfigureOsToShowYouReportNonNe" +
                        "xtYourLogonToTheSystemIfAnyErrorsNorWarningsWillBeRegisteredDuringTheBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your backup is password protected, please type password here:.
        /// </summary>
        internal static string IfYourBackupIsPasswordProtectedPleaseTypePasswordHere {
            get {
                return ResourceManager.GetString("IfYourBackupIsPasswordProtectedPleaseTypePasswordHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important:
        ///
        ///Backup should be password protected. If NOT, program will SKIP its copying to this storage.
        /// </summary>
        internal static string ImportantNNbackupShouldBePasswordProtectedIfNotProgramWillSkipItsCopyingToThisStorage {
            get {
                return ResourceManager.GetString("ImportantNNbackupShouldBePasswordProtectedIfNotProgramWillSkipItsCopyingToThisSto" +
                        "rage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremental backup.
        /// </summary>
        internal static string IncrementalBackup {
            get {
                return ResourceManager.GetString("IncrementalBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most basic form of incremental backup consists of identifying, recording and thus, preserving only those files that have changed since the last backup. Since changes are typically low, incremental backups are much smaller and quicker than full backups. For instance, following a full backup on Friday, a Monday backup will contain only those files that changed since Friday. A Tuesday backup contains only those files that changed since Monday, and so on. A full restoration of data will naturally be slower, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IncrementalBackupDescription {
            get {
                return ResourceManager.GetString("IncrementalBackupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress....
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this place you can add locations where you would like your backup to be copied after completion of backup.
        /// </summary>
        internal static string InThisPlaceYouCanAddLocationsWhereYouWouldLikeYourBackupToBeCopiedAfterCompletionOfBackup {
            get {
                return ResourceManager.GetString("InThisPlaceYouCanAddLocationsWhereYouWouldLikeYourBackupToBeCopiedAfterCompletion" +
                        "OfBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument(s) passed to the program.
        ///
        ///Please refer to manual for the complete list of parameters!.
        /// </summary>
        internal static string InvalidArgumentSPassedToTheProgramNNpleaseReferToManualForTheCompleteListOfParameters {
            get {
                return ResourceManager.GetString("InvalidArgumentSPassedToTheProgramNNpleaseReferToManualForTheCompleteListOfParame" +
                        "ters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to backup.
        /// </summary>
        internal static string ItemsToBackup {
            get {
                return ResourceManager.GetString("ItemsToBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs location:.
        /// </summary>
        internal static string LogsLocation {
            get {
                return ResourceManager.GetString("LogsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute:.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous options.
        /// </summary>
        internal static string MiscellaneousOptions {
            get {
                return ResourceManager.GetString("MiscellaneousOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify....
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is empty..
        /// </summary>
        internal static string NameIsEmpty {
            get {
                return ResourceManager.GetString("NameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network places are not allowed to be added to the list of backup items!.
        /// </summary>
        internal static string NetworkPlacesAreNotAllowedToBeAddedToTheListOfBackupItems {
            get {
                return ResourceManager.GetString("NetworkPlacesAreNotAllowedToBeAddedToTheListOfBackupItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network storage....
        /// </summary>
        internal static string NetworkStorage {
            get {
                return ResourceManager.GetString("NetworkStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Storage Configuration.
        /// </summary>
        internal static string NetworkStorageConfiguration {
            get {
                return ResourceManager.GetString("NetworkStorageConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network storages.
        /// </summary>
        internal static string NetworkStorages {
            get {
                return ResourceManager.GetString("NetworkStorages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network storages are not allowed to be pointed here!.
        /// </summary>
        internal static string NetworkStoragesAreNotAllowedToBePointedHere {
            get {
                return ResourceManager.GetString("NetworkStoragesAreNotAllowedToBePointedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0} version is available.
        ///
        ///Changes are:
        ///{1}
        ///
        ///Program will now open browser with the download page.
        /// </summary>
        internal static string New0VersionIsAvailableNNchangesAreN1NNprogramWillNowOpenBrowserWithTheDownloadPage {
            get {
                return ResourceManager.GetString("New0VersionIsAvailableNNchangesAreN1NNprogramWillNowOpenBrowserWithTheDownloadPag" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Backup Task Title.
        /// </summary>
        internal static string NewBackupTaskTitle {
            get {
                return ResourceManager.GetString("NewBackupTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Backup Task Wizard.
        /// </summary>
        internal static string NewBackupTaskWizard {
            get {
                return ResourceManager.GetString("NewBackupTaskWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Event Task - Configurator.
        /// </summary>
        internal static string NewEventTaskConfigurator {
            get {
                return ResourceManager.GetString("NewEventTaskConfigurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Open Logs.
        /// </summary>
        internal static string OpenLogs {
            get {
                return ResourceManager.GetString("OpenLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open logs folder in Explorer....
        /// </summary>
        internal static string OpenLogsFolderInExplorer {
            get {
                return ResourceManager.GetString("OpenLogsFolderInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other options.
        /// </summary>
        internal static string OtherOptions {
            get {
                return ResourceManager.GetString("OtherOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passive.
        /// </summary>
        internal static string Passive {
            get {
                return ResourceManager.GetString("Passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one destination place..
        /// </summary>
        internal static string PleaseAddAtLeastOneDestinationPlace {
            get {
                return ResourceManager.GetString("PleaseAddAtLeastOneDestinationPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check items to compress!.
        /// </summary>
        internal static string PleaseCheckItemsToCompress {
            get {
                return ResourceManager.GetString("PleaseCheckItemsToCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check storages where to copy backup image!.
        /// </summary>
        internal static string PleaseCheckStoragesWhereToCopyBackupImage {
            get {
                return ResourceManager.GetString("PleaseCheckStoragesWhereToCopyBackupImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing State.
        /// </summary>
        internal static string ProcessingState {
            get {
                return ResourceManager.GetString("ProcessingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process priority:.
        /// </summary>
        internal static string ProcessPriority {
            get {
                return ResourceManager.GetString("ProcessPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program:.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program does not exist..
        /// </summary>
        internal static string ProgramDoesNotExist {
            get {
                return ResourceManager.GetString("ProgramDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection of backup with password. It is required when you want your data to be copied somewhere over the network.
        /// </summary>
        internal static string ProtectionOfBackupWithPasswordItIsRequiredWhenYouWantYourDataToBeCopiedSomewhereOverTheNetwork {
            get {
                return ResourceManager.GetString("ProtectionOfBackupWithPasswordItIsRequiredWhenYouWantYourDataToBeCopiedSomewhereO" +
                        "verTheNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put off making backup till processor\&apos;s  loading will be less then.
        /// </summary>
        internal static string PutOffMakingBackupTillProcessorSLoadingWillBeLessThen {
            get {
                return ResourceManager.GetString("PutOffMakingBackupTillProcessorSLoadingWillBeLessThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        internal static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover!.
        /// </summary>
        internal static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from list.
        /// </summary>
        internal static string RemoveFromList {
            get {
                return ResourceManager.GetString("RemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected logs.
        /// </summary>
        internal static string RemoveSelectedLogs {
            get {
                return ResourceManager.GetString("RemoveSelectedLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the selected backup task....
        /// </summary>
        internal static string RemovesTheSelectedBackupTask {
            get {
                return ResourceManager.GetString("RemovesTheSelectedBackupTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove succesfull logs.
        /// </summary>
        internal static string RemoveSuccesfullLogs {
            get {
                return ResourceManager.GetString("RemoveSuccesfullLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration master.
        /// </summary>
        internal static string RestorationMaster {
            get {
                return ResourceManager.GetString("RestorationMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Data....
        /// </summary>
        internal static string RestoreData {
            get {
                return ResourceManager.GetString("RestoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Restore default logs location.
        /// </summary>
        internal static string RestoreDefaultLogsLocation {
            get {
                return ResourceManager.GetString("RestoreDefaultLogsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review log of last backup....
        /// </summary>
        internal static string ReviewLogOfLastBackup {
            get {
                return ResourceManager.GetString("ReviewLogOfLastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs backup....
        /// </summary>
        internal static string RunsBackup {
            get {
                return ResourceManager.GetString("RunsBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Run.
        /// </summary>
        internal static string SaveAndRun {
            get {
                return ResourceManager.GetString("SaveAndRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling.
        /// </summary>
        internal static string Scheduling {
            get {
                return ResourceManager.GetString("Scheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set compression degree.
        /// </summary>
        internal static string SetCompressionDegree {
            get {
                return ResourceManager.GetString("SetCompressionDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown PC.
        /// </summary>
        internal static string ShutdownPc {
            get {
                return ResourceManager.GetString("ShutdownPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip copying and write a warning into log if backup exceeds.
        /// </summary>
        internal static string SkipCopyingAndWriteAWarningIntoLogIfBackupExceeds {
            get {
                return ResourceManager.GetString("SkipCopyingAndWriteAWarningIntoLogIfBackupExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the folder where to store back-up:.
        /// </summary>
        internal static string SpecifyTheFolderWhereToStoreBackUp {
            get {
                return ResourceManager.GetString("SpecifyTheFolderWhereToStoreBackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage name:.
        /// </summary>
        internal static string StorageName {
            get {
                return ResourceManager.GetString("StorageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfull.
        /// </summary>
        internal static string Succesfull {
            get {
                return ResourceManager.GetString("Succesfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPPORT.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend PC.
        /// </summary>
        internal static string SuspendPc {
            get {
                return ResourceManager.GetString("SuspendPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target folder should have UNC name(for example:\\server1\sharedResource1)!.
        /// </summary>
        internal static string TargetFolderShouldHaveUncNameForExampleServer1Sharedresource1 {
            get {
                return ResourceManager.GetString("TargetFolderShouldHaveUncNameForExampleServer1Sharedresource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task to run.
        /// </summary>
        internal static string TaskToRun {
            get {
                return ResourceManager.GetString("TaskToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best choice is &quot;low&quot; in almost all cases.
        /// </summary>
        internal static string TheBestChoiceIsLowInAlmostAllCases {
            get {
                return ResourceManager.GetString("TheBestChoiceIsLowInAlmostAllCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items to backup!
        ///
        ///You can specify the data to backup in Configurator in &apos;What&apos; settings group..
        /// </summary>
        internal static string ThereAreNoItemsToBackupNNyouCanSpecifyTheDataToBackupInConfiguratorInWhatSettingsGroup {
            get {
                return ResourceManager.GetString("ThereAreNoItemsToBackupNNyouCanSpecifyTheDataToBackupInConfiguratorInWhatSettings" +
                        "Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no specified places where to store backup!
        ///
        ///You can add some storages in Configurator in &apos;Where&apos; settings group..
        /// </summary>
        internal static string ThereAreNoSpecifiedPlacesWhereToStoreBackupNNyouCanAddSomeStoragesInConfiguratorInWhereSettingsGroup {
            get {
                return ResourceManager.GetString("ThereAreNoSpecifiedPlacesWhereToStoreBackupNNyouCanAddSomeStoragesInConfiguratorI" +
                        "nWhereSettingsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This master will help you to create a new task.
        /// </summary>
        internal static string ThisMasterWillHelpYouToCreateANewTask {
            get {
                return ResourceManager.GetString("ThisMasterWillHelpYouToCreateANewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mode is for getting support.
        /// </summary>
        internal static string ThisModeIsForGettingSupport {
            get {
                return ResourceManager.GetString("ThisModeIsForGettingSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already taken. Try another one..
        /// </summary>
        internal static string ThisNameIsAlreadyTakenTryAnotherOne {
            get {
                return ResourceManager.GetString("ThisNameIsAlreadyTakenTryAnotherOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2007-2008 Kuchuk Siarhei Alexandrovich, Cuchuk.Sergey@gmail.com.
        /// </summary>
        internal static string TranslationAuthor {
            get {
                return ResourceManager.GetString("TranslationAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use right-click mouse on selected item to restore it.
        /// </summary>
        internal static string UseRightClickMouseOnSelectedItemToRestoreIt {
            get {
                return ResourceManager.GetString("UseRightClickMouseOnSelectedItemToRestoreIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to utility for creating backups.
        ///
        ///Web-sites: https://github.com/drweb86/butil
        ///
        ///Localization created by:
        ///.
        /// </summary>
        internal static string UtilityForCreatingBackupsNNwebSitesHttpsGithubComDrweb86ButilNNlocalizationCreatedByN {
            get {
                return ResourceManager.GetString("UtilityForCreatingBackupsNNwebSitesHttpsGithubComDrweb86ButilNNlocalizationCreate" +
                        "dByN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View selected logs....
        /// </summary>
        internal static string ViewSelectedLogs {
            get {
                return ResourceManager.GetString("ViewSelectedLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was asked to update options.
        /// </summary>
        internal static string WasAskedToUpdateOptions {
            get {
                return ResourceManager.GetString("WasAskedToUpdateOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellcome to Backup Task Creation Wizard!.
        /// </summary>
        internal static string WellcomeToBackupTaskCreationWizard {
            get {
                return ResourceManager.GetString("WellcomeToBackupTaskCreationWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellcome to Backup Wizard!.
        /// </summary>
        internal static string WellcomeToBackupWizard {
            get {
                return ResourceManager.GetString("WellcomeToBackupWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What?.
        /// </summary>
        internal static string What {
            get {
                return ResourceManager.GetString("What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When?.
        /// </summary>
        internal static string When {
            get {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where?.
        /// </summary>
        internal static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While backup is in progress you can continue work. 
        ///
        ///To restore progress form just click on this icon in tray.
        /// </summary>
        internal static string WhileBackupIsInProgressYouCanContinueWorkNNtoRestoreProgressFormJustClickOnThisIconInTray {
            get {
                return ResourceManager.GetString("WhileBackupIsInProgressYouCanContinueWorkNNtoRestoreProgressFormJustClickOnThisIc" +
                        "onInTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory:.
        /// </summary>
        internal static string WorkingDirectory {
            get {
                return ResourceManager.GetString("WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory does not exist..
        /// </summary>
        internal static string WorkingDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("WorkingDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works fine!.
        /// </summary>
        internal static string WorksFine {
            get {
                return ResourceManager.GetString("WorksFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to apply modified settings?.
        /// </summary>
        internal static string WouldYouLikeToApplyModifiedSettings {
            get {
                return ResourceManager.GetString("WouldYouLikeToApplyModifiedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you lile to remove the backup task &apos;{0}&apos; ?.
        /// </summary>
        internal static string WouldYouLileToRemoveTheBackupTask0 {
            get {
                return ResourceManager.GetString("WouldYouLileToRemoveTheBackupTask0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can set days and times when you want to start this backup job.
        /// </summary>
        internal static string YouCanSetDaysAndTimesWhenYouWantToStartThisBackupJob {
            get {
                return ResourceManager.GetString("YouCanSetDaysAndTimesWhenYouWantToStartThisBackupJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version!.
        /// </summary>
        internal static string YouHaveTheLatestVersion {
            get {
                return ResourceManager.GetString("YouHaveTheLatestVersion", resourceCulture);
            }
        }
    }
}
