//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUtil.Ghost.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUtil.Ghost.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup finished.
        /// </summary>
        internal static string BackupFinished {
            get {
                return ResourceManager.GetString("BackupFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup now in a progress....
        /// </summary>
        internal static string BackupNowInAProgress {
            get {
                return ResourceManager.GetString("BackupNowInAProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup started....
        /// </summary>
        internal static string BackupStarted {
            get {
                return ResourceManager.GetString("BackupStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup tool BUtil.
        /// </summary>
        internal static string BackupToolButil {
            get {
                return ResourceManager.GetString("BackupToolButil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUtil Scheduler is running...\n\nTo not see this message again you should run the scheduler with parameter.\nPlease see the documentation for details..
        /// </summary>
        internal static string ButilSchedulerIsRunningNNtoNotSeeThisMessageAgainYouShouldRunTheSchedulerWithParameterNpleaseSeeTheDocumentationForDetails {
            get {
                return ResourceManager.GetString("ButilSchedulerIsRunningNNtoNotSeeThisMessageAgainYouShouldRunTheSchedulerWithPara" +
                        "meterNpleaseSeeTheDocumentationForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file log due to crytical error {0}.
        /// </summary>
        internal static string CannotOpenFileLogDueToCryticalError0 {
            get {
                return ResourceManager.GetString("CannotOpenFileLogDueToCryticalError0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In 8 minutes scheduled backup will start.
        /// </summary>
        internal static string In8MinutesScheduledBackupWillStart {
            get {
                return ResourceManager.GetString("In8MinutesScheduledBackupWillStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New backup will start in {0}.
        /// </summary>
        internal static string NewBackupWillStartIn0 {
            get {
                return ResourceManager.GetString("NewBackupWillStartIn0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one task uses scheduler.\nYou&apos;d open Configurator on &apos;When&apos; tab.\n\nApplication will now close..
        /// </summary>
        internal static string NoOneTaskUsesSchedulerNyoudOpenConfiguratorOnWhenTabNNapplicationWillNowClose {
            get {
                return ResourceManager.GetString("NoOneTaskUsesSchedulerNyoudOpenConfiguratorOnWhenTabNNapplicationWillNowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options are damaged. Please reconfigure them in Configurator.
        /// </summary>
        internal static string OptionsAreDamagedPleaseReconfigureThemInConfigurator {
            get {
                return ResourceManager.GetString("OptionsAreDamagedPleaseReconfigureThemInConfigurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is wrong. \n\nFor the complete parameters list please see documentation..
        /// </summary>
        internal static string ParameterIsWrongNNforTheCompleteParametersListPleaseSeeDocumentation {
            get {
                return ResourceManager.GetString("ParameterIsWrongNNforTheCompleteParametersListPleaseSeeDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler start up is forbidden.\nTo change it you can open the Configurator.\n\nApplication will now close..
        /// </summary>
        internal static string SchedulerStartUpIsForbiddenNtoChangeItYouCanOpenTheConfiguratorNNapplicationWillNowClose {
            get {
                return ResourceManager.GetString("SchedulerStartUpIsForbiddenNtoChangeItYouCanOpenTheConfiguratorNNapplicationWillN" +
                        "owClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping the backup....
        /// </summary>
        internal static string StoppingTheBackup {
            get {
                return ResourceManager.GetString("StoppingTheBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no options file. \nYou can configure application in Confirurator.\n\nApplication will now close..
        /// </summary>
        internal static string ThereAreNoOptionsFileNyouCanConfigureApplicationInConfiruratorNNapplicationWillNowClose {
            get {
                return ResourceManager.GetString("ThereAreNoOptionsFileNyouCanConfigureApplicationInConfiruratorNNapplicationWillNo" +
                        "wClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second copy of BUtil scheduler ran.\n\nNow this copy will terminate..
        /// </summary>
        internal static string TheSecondCopyOfButilSchedulerRanNNnowThisCopyWillTerminate {
            get {
                return ResourceManager.GetString("TheSecondCopyOfButilSchedulerRanNNnowThisCopyWillTerminate", resourceCulture);
            }
        }
    }
}
