  name: butil
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: BUtil creates incremental backups and imports multimedia on your PC with deduplication and FTPS, SMB/CIFS transports support.
  grade: devel # must be 'stable' to release into candidate/stable channels
  base: core22
  confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  butil:
    plugin: dotnet
    dotnet-build-configuration: Release
    dotnet-self-contained-runtime-identifier: linux-x64
    source: ./sources
    build-packages:
      - dotnet-sdk-8.0
    stage-packages:
      - 7zip
      - curl
      - apt-transport-https
      - gnupg2
      - powershell

apps:
  BUtil:
    command: dotnet ./bin/butil-ui.Desktop.dll