name: butil
version: '3'
grade: devel # must be 'stable' to release into candidate/stable channels
summary: Backup your data. Import photos from phone via WI-FI and more.
description: |
  Backup your data. Import photos from phone via WI-FI and more.
  Features include
  - Incremental backup with deduplication of files and FTPS, SMB/CIFS transports support;
  - Import media - Import audios, photos, videos from SD Card of camera, recorder; photos and videos from your phone via WI-FI through FTPS Server application using template file names;
  - Console for automation scheduling;
  - Strong 7-zip compression and AES-256 encryption.
  Minimum Ubuntu version should be 23.10.

base: core22

confinement: classic
compression: lzo

architectures: 
  - build-on: amd64
    build-for: all

apps:
  butil:
    command: ./butil-ui.Desktop.dll
    plugs:
      - desktop
      - desktop-legacy
  butilc:
    command: ./butilc.dll

parts:
  butil:
    plugin: dotnet
    dotnet-build-configuration: Release
    source: ./sources
    build-packages:
      - dotnet-sdk-7.0
    stage-packages:
      - dotnet-sdk-7.0
      - libicu70
      - 7zip
    stage-snaps:
      - powershell

lint:
  ignore:
    - classic 
    - library