package-repositories:
  - type: apt
    ppa: snappy-dev/snapcraft-daily

name: butil
grade: stable
summary: Backup your data. Import photos from phone via WI-FI and more.
description: |
  Backup your data. Import photos from phone via WI-FI and more.
  Features include
  - Incremental backup with deduplication of files and FTPS, SMB/CIFS transports support;
  - Import media - Import audios, photos, videos from SD Card of camera, recorder; photos and videos from your phone via WI-FI through FTPS Server application using template file names;
  - Console for automation scheduling;
  - Strong 7-zip compression and AES-256 encryption.
  Minimum Ubuntu version should be 23.10.
license: GPL-3.0+ OR MIT OR MS-PL
issues: https://github.com/drweb86/butil/issues
source-code: https://github.com/drweb86/butil

base: core22

architectures:
  - amd64

confinement: classic
compression: lzo

apps:
  ui:
    command: bin/butil-ui.Desktop
    plugs:
      - desktop
  cli:
    command: bin/butilc

parts:
  butil:
    plugin: dotnet
    dotnet-build-configuration: Release
    source: https://github.com/drweb86/butil
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `(git describe --tags --abbrev=0) 2>/dev/null`
    build-packages:
      - dotnet-sdk-7.0
      - git
    override-build: |     
      cd ./sources
      dotnet publish /p:Version=$SNAPCRAFT_PROJECT_VERSION /p:AssemblyVersion=$SNAPCRAFT_PROJECT_VERSION -r linux-x64 -c Release --self-contained true -o $SNAPCRAFT_PART_INSTALL/bin/
      chmod 0755 $SNAPCRAFT_PART_INSTALL/bin/butil-ui.Desktop
      chmod 0755 $SNAPCRAFT_PART_INSTALL/bin/butilc
    stage-packages:
      - 7zip

lint:
  ignore:
    - classic 
    - library